// 新增 buildscript
buildscript {
    dependencies {
        // Note: If you use HuaWei or Honor push, you need to add the following dependencies
        classpath("com.android.tools.build:gradle:8.6.1")
    }
}
plugins {
    id 'com.android.application' version '8.6.1' apply false
    id 'com.android.library' version '8.6.1' apply false
}

if (JavaVersion.current().isJava8Compatible()) {
    allprojects {
        tasks.withType(Javadoc) {
            options.addStringOption('Xdoclint:none', '-quiet')
        }
    }
}

ext{
    if(!project.hasProperty('sdkVersion')){
        sdkVersion = '3.2.3'
    }
    if(!project.hasProperty('stagingRepositoryId')){
        stagingRepositoryId = 'ioagorartc-1000'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext{
    if(!project.hasProperty('isAarRelease')){
        isAarRelease = false;
    }
    if(!project.hasProperty('isLite')){
        isLite = false;
    }
    if(!project.hasProperty('sdkVersion')){
        sdkVersion = '3.2.3'
    }
    if(!project.hasProperty('isTravis')) {
        isTravis = false
    }
    if(!project.hasProperty('stagingRepositoryId')){
        stagingRepositoryId = 'iohyphenate-1000'
    }
}

//apply plugin: 'io.codearte.nexus-staging'