group = "io.agora.rtc"
archivesBaseName = "chat-uikit"
version = project.sdkVersion //发布aar的库版本

apply plugin: 'maven-publish'
apply plugin: 'signing'

def repositoryId = project.stagingRepositoryId

def localProperties = new Properties()
def localPropertiesFile = project.rootProject.file('local.properties')
localPropertiesFile.withInputStream { localProperties.load(it) }

Properties properties = new Properties()
def mavenDir = localProperties.getProperty('maven.dir')
def mavenPropertiesFile = project.file("${mavenDir}/project.properties")
mavenPropertiesFile.withInputStream { properties.load(it) }

def ossrhUsername = properties.getProperty('ossrhUsername')
def ossrhPassword = properties.getProperty('ossrhPassword')

def signingKeyId = properties.getProperty("signing.keyId")
def signingKeyRingFile = project.file("${mavenDir}/${properties.getProperty("signing.secretKeyRingFile")}")
def signingPassword = properties.getProperty("signing.password")

ext."signing.keyId" = signingKeyId
ext."signing.secretKeyRingFile" = signingKeyRingFile.absolutePath
ext."signing.password" = signingPassword

android {
    publishing {
        singleVariant('release') {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

tasks.register('sourcesJar') {
    dependsOn tasks.named('sourceReleaseJar')
}

tasks.register('javadocJar') {
    dependsOn tasks.named('javaDocReleaseJar')
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release

                groupId = project.group
                artifactId = project.archivesBaseName
                version = project.version

                pom {
                    name = project.archivesBaseName
                    packaging = 'aar'
                    description = 'Agora SDK UIKit'
                    url = 'http://maven.apache.org'

                    scm {
                        connection = 'scm:git:https://github.com/AgoraIO-Usecase/AgoraChat-UIKit-android.git'
                        developerConnection = 'scm:git:https://github.com/AgoraIO-Usecase/AgoraChat-UIKit-android.git'
                        url = 'https://github.com/AgoraIO-Usecase/AgoraChat-UIKit-android'
                    }

                    licenses {
                        license {
                            name = 'AGORA SDK License'
                            url = 'https://github.com/AgoraIO/full-sdk/blob/master/LICENSE'
                        }
                    }

                    developers {
                        developer {
                            name = 'agorabuilder'
                            email = 'zhaoliang@agora.io'
                            organization = 'https://github.com/AgoraIO'
                            url = 'https://www.agora.io/cn'
                        }
                    }
                }
            }
        }

        repositories {
            maven {
                name = 'Ossrh'
                url = version.toString().endsWith('SNAPSHOT')
                        ? uri('https://oss.sonatype.org/content/repositories/snapshots/')
                        : uri('https://oss.sonatype.org/service/local/staging/deploy/maven2/')
                credentials {
                    username = ossrhUsername
                    password = ossrhPassword
                }
            }
            maven {
                name = 'manual'
                url = uri("${rootProject.buildDir}/manual-maven")
            }
        }
    }

    signing {
        sign publishing.publications.release
    }
}

if (project.plugins.hasPlugin('io.codearte.nexus-staging')) {
    nexusStaging {
        packageGroup = "$group"
        stagingProfileId = "$group"
        username = ossrhUsername
        password = ossrhPassword
        stagingRepositoryId = repositoryId
    }
}
