pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url = uri("https://maven.aliyun.com/repository/public/")}
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://maven.aliyun.com/repository/public/")}
    }
}

rootProject.name = "AgoraChat-UIKit-android"

include ':chat-uikit'
include ':app'
//include ':hyphenatechatsdk'
//project(':hyphenatechatsdk').projectDir = new File('../emclient-android/hyphenatechatsdk')