# -*- coding: UTF-8 -*-
import os
import argparse
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

# 调用：python3 rename_file_and_update_content.py ./target_folder --rename-files --replace-content
# directory：目标文件夹路径。
# --rename-files：如果指定此参数，则会执行文件重命名操作。
# --replace-content：如果指定此参数，则会执行文件内容替换操作。


# 预置的文件名映射（不包含文件后缀）
files_map = {
    #kotlin
    "EaseIM": "ChatUIKitClient",
    "EaseIMConfig": "ChatUIKitConfig",
    "EaseBaseViewModel": "ChatUIKitBaseViewModel",
    "EaseReactionUserListViewModel": "ChatUIKitReactionUserListViewModel",
    "EaseChatReactionViewModel": "ChatUIKitReactionViewModel",
    "EaseMessageReactionListViewModel": "ChatUIKitReactionListViewModel",
    "EaseChatViewModel": "ChatUIKitViewModel",
    "EaseMessageListViewModel": "ChatUIKitMessageListViewModel",
    "EaseGroupViewModel": "ChatUIKitGroupViewModel",
    "EaseChatHistoryViewModel": "ChatUIKitHistoryViewModel",
    "EaseContactListViewModel": "ChatUIKitContactListViewModel",
    "EaseSearchViewModel": "ChatUIKitSearchViewModel",
    "EaseChatMessageReplyViewModel": "ChatUIKitMessageReplyViewModel",
    "EaseConversationListViewModel": "ChatUIKitConversationListViewModel",
    "EaseNotificationViewModel": "ChatUIKitNotificationViewModel",
    "EaseChatThreadViewModel": "ChatUIKitThreadViewModel",
    "EaseConversationRepository": "ChatUIKitConversationRepository",
    "EaseChatManagerRepository": "ChatUIKitManagerRepository",
    "EaseSearchRepository": "ChatUIKitSearchRepository",
    "EaseNotificationRepository": "ChatUIKitNotificationRepository",
    "EaseChatThreadRepository": "ChatUIKitThreadRepository",
    "EaseReportRepository": "ChatUIKitReportRepository",
    "EaseGroupRepository": "ChatUIKitGroupRepository",
    "EaseContactListRepository": "ChatUIKitContactListRepository",
    "EaseSearchEditText": "ChatUIKitSearchEditText",
    "EaseSearchView": "ChatUIKitSearchView",
    "EaseWaveView": "ChatUIKitWaveView",
    "EaseTitleBar": "ChatUIKitTitleBar",
    "EaseArrowItemView": "ChatUIKitArrowItemView",
    "EaseSidebar": "ChatUIKitSidebar",
    "EaseCustomAvatarView": "ChatUIKitCustomAvatarView",
    "EaseFlowLayout": "ChatUIKitFlowLayout",
    "EaseSwitchItemView": "ChatUIKitSwitchItemView",
    "EaseDividerGridItemDecoration": "ChatUIKitDividerGridItemDecoration",
    "EaseImageView": "ChatUIKitImageView",
    "EaseInputEditText": "ChatUIKitInputEditText",
    "EaseChatRowCombine": "ChatUIKitRowCombine",
    "EaseChatRowVideo": "ChatUIKitRowVideo",
    "EaseChatRowImage": "ChatUIKitRowImage",
    "EaseChatRowThreadUnknown": "ChatUIKitRowThreadUnknown",
    "EaseChatRowAlert": "ChatUIKitRowAlert",
    "EaseChatRowUserCard": "ChatUIKitRowUserCard",
    "EaseChatRowThreadNotify": "ChatUIKitRowThreadNotify",
    "EaseChatRowVoice": "ChatUIKitRowVoice",
    "EaseChatRowLocation": "ChatUIKitRowLocation",
    "EaseChatRowCustom": "ChatUIKitRowCustom",
    "EaseChatRowBigExpression": "ChatUIKitRowBigExpression",
    "EaseChatRowUnknown": "ChatUIKitRowUnknown",
    "EaseChatRowText": "ChatUIKitRowText",
    "EaseChatRowUnsent": "ChatUIKitRowUnsent",
    "EaseChatRow": "ChatUIKitRow",
    "EaseChatRowFile": "ChatUIKitRowFile",
    "EasePhotoView": "ChatUIKitPhotoView",
    "EaseGroupProfileProvider": "ChatUIKitGroupProfileProvider",
    "EaseUserProfileProvider": "ChatUIKitUserProfileProvider",
    "EaseEmojiconInfoProvider": "ChatUIKitEmojiconInfoProvider",
    "EaseCustomActivityRoute": "ChatUIKitCustomActivityRoute",
    "EaseSettingsProvider": "ChatUIKitSettingsProvider",
    "EaseIMCache": "ChatUIKitCache",
    "EaseError": "ChatUIKitError",
    "EaseConstant": "ChatUIKitConstant",
    "EaseIMClientImpl": "ChatUIKitClientImpl",
    "EaseAvatarShape": "ChatUIKitAvatarShape",
    "EaseListViewType": "ChatUIKitListViewType",
    "EaseGroupMemberType": "ChatUIKitGroupMemberType",
    "EaseTranslationLanguageType": "ChatUIKitTranslationLanguageType",
    "EaseChatFinishReason": "ChatUIKitFinishReason",
    "EaseCacheType": "ChatUIKitCacheType",
    "EaseReplyMap": "ChatUIKitReplyMap",
    "EaseFlowBus": "ChatUIKitFlowBus",
    "EaseImageUtils": "ChatUIKitImageUtils",
    "EaseVoiceLengthUtils": "ChatUIKitVoiceLengthUtils",
    "EaseCompat": "ChatUIKitCompat",
    "EaseFileUtils": "ChatUIKitFileUtils",
    "EaseProfile": "ChatUIKitProfile",
    "EaseUser": "ChatUIKitUser",
    "EaseBottomSheetChildHelper": "ChatUIKitBottomSheetChildHelper",
    "EaseContactBottomSheetFragment": "ChatUIKitContactBottomSheetFragment",
    "EaseAlertDialog": "ChatUIKitAlertDialog",
    "EaseBottomSheetContainerHelper": "ChatUIKitBottomSheetContainerHelper",
    "EaseNewChatBottomSheetFragment": "ChatUIKitNewBottomSheetFragment",
    "EaseDingMessageHelper": "ChatUIKitDingMessageHelper",
    "EasePreferenceManager": "ChatUIKitPreferenceManager",
    "EaseAtMessageHelper": "ChatUIKitAtMessageHelper",
    "EaseNotifier": "ChatUIKitNotifier",
    "EaseChatRowVoicePlayer": "ChatUIKitRowVoicePlayer",
    "EaseMenuFilterHelper": "ChatUIKitMenuFilterHelper",
    "EaseEmojiHelper": "ChatUIKitEmojiHelper",
    "EaseTimerHelper": "ChatUIKitTimerHelper",
    "EaseThreadNotifyHelper": "ChatUIKitThreadNotifyHelper",
    "EaseVoiceRecorder": "ChatUIKitVoiceRecorder",
    "EaseTitleBarHelper": "ChatUIKitTitleBarHelper",
    "EaseSystemMsgConfig": "ChatUIKitSystemMsgConfig",
    "EaseBottomMenuConfig": "ChatUIKitBottomMenuConfig",
    "EaseDetailMenuConfig": "ChatUIKitDetailMenuConfig",
    "EaseAvatarConfig": "ChatUIKitAvatarConfig",
    "EaseChatConfig": "ChatUIKitConfig",
    "EaseMultiDeviceEventConfig": "ChatUIKitMultiDeviceEventConfig",
    "EaseDateFormatConfig": "ChatUIKitDateFormatConfig",
    "EaseHeaderItemConfig": "ChatUIKitHeaderItemConfig",
    "EaseCustomMentionItemConfig": "ChatUIKitCustomMentionItemConfig",
    "EaseMenuDialog": "ChatUIKitMenuDialog",
    "EaseMenuAdapter": "ChatUIKitMenuAdapter",
    "EaseMenuPopupWindow": "ChatUIKitMenuPopupWindow",
    "EaseMenuHelper": "ChatUIKitMenuHelper",
    "EaseMenuItemView": "ChatUIKitMenuItemView",
    "EaseChatMenuHelper": "ChatUIKitChatMenuHelper",
    "EaseChatExtendMenuDialog": "ChatUIKitExtendMenuDialog",
    "EaseSelectPopAdapter": "ChatUIKitSelectPopAdapter",
    "EaseDefaultEmojiconDatas": "ChatUIKitDefaultEmojiconDatas",
    "EaseEmojiconGroupEntity": "ChatUIKitEmojiconGroupEntity",
    "EaseEvent": "ChatUIKitEvent",
    "EasePreview": "ChatUIKitPreview",
    "EaseGroupProfile": "ChatUIKitGroupProfile",
    "EaseMenuItem": "ChatUIKitMenuItem",
    "EaseConversation": "ChatUIKitConversation",
    "EaseEmojicon": "ChatUIKitEmojicon",
    "EaseReactionEmojiconEntity": "ChatUIKitReactionEmojiconEntity",
    "EaseCustomHeaderItem": "ChatUIKitCustomHeaderItem",
    "EaseSize": "ChatUIKitSize",
    "EasePager": "ChatUIKitPager",
    "EaseReaction": "ChatUIKitReaction",
    "EaseContactsListFragment": "ChatUIKitContactsListFragment",
    "EaseContactDetailsActivity": "ChatUIKitContactDetailsActivity",
    "EaseBlockListFragment": "ChatUIKitBlockListFragment",
    "EaseBlockListActivity": "ChatUIKitBlockListActivity",
    "EaseContactCheckActivity": "ChatUIKitContactCheckActivity",
    "EaseContactHeaderConfigBinding": "ChatUIKitContactHeaderConfigBinding",
    "EaseContactHeaderConfig": "ChatUIKitContactHeaderConfig",
    "EaseListViewHolderFactory": "ChatUIKitListViewHolderFactory",
    "EaseContactListAdapter": "ChatUIKitContactListAdapter",
    "EaseContactDetailItemAdapter": "ChatUIKitContactDetailItemAdapter",
    "EaseCustomHeaderAdapter": "ChatUIKitCustomHeaderAdapter",
    "EaseUserContactItem": "ChatUIKitUserContactItem",
    "EaseGroupMemberViewHolder": "ChatUIKitGroupMemberViewHolder",
    "EaseContactListLayout": "ChatUIKitContactListLayout",
    "EaseChatFragment": "UIKitChatFragment",
    "EaseNewChatFragment": "UIKitNewChatFragment",
    "EaseAddUserCardFragment": "ChatUIKitAddUserCardFragment",
    "EaseMessageMenuReactionView": "ChatUIKitMessageMenuReactionView",
    "EaseReactionUserListFragment": "ChatUIKitReactionUserListFragment",
    "EaseChatReactionsDialog": "ChatUIKitReactionsDialog",
    "EaseMessageReactionsDialog": "ChatUIKitMessageReactionsDialog",
    "EaseChatMessageReactionView": "ChatUIKitMessageReactionView",
    "EaseMessageReactionViewHolderFactory": "ChatUIKitMessageReactionViewHolderFactory",
    "EaseReactionUserAdapter": "ChatUIKitReactionUserAdapter",
    "EaseMessageReactionAdapter": "ChatUIKitMessageReactionAdapter",
    "EaseReactionUserPagerAdapter": "ChatUIKitReactionUserPagerAdapter",
    "EaseReactionAddViewHolder": "ChatUIKitReactionAddViewHolder",
    "EaseReactionDefaultViewHolder": "ChatUIKitReactionDefaultViewHolder",
    "EaseReactionMoreViewHolder": "ChatUIKitReactionMoreViewHolder",
    "EaseReactionNormalViewHolder": "ChatUIKitReactionNormalViewHolder",
    "EaseChatPinMessageListViewGroup": "ChatUIKitPinMessageListViewGroup",
    "EaseChatPinItemSpaceDecoration": "ChatUIKitPinItemSpaceDecoration",
    "EaseChatPinDefaultViewHolder": "ChatUIKitPinDefaultViewHolder",
    "EaseChatPinTextMessageViewHolder": "ChatUIKitPinTextMessageViewHolder",
    "EaseChatPinImageMessageViewHolder": "ChatUIKitPinImageMessageViewHolder",
    "EaseChatMessageTranslationView": "ChatUIKitMessageTranslationView",
    "EaseChatMessageItemConfig": "ChatUIKitMessageItemConfig",
    "EaseChatHistoryFragment": "ChatUIKitHistoryFragment",
    "EaseChatHistoryLayout": "ChatUIKitHistoryLayout",
    "EaseChatHistoryAdapter": "ChatUIKitHistoryAdapter",
    "EaseChatRowHistoryImage": "ChatUIKitRowHistoryImage",
    "EaseChatRowHistoryVideo": "ChatUIKitRowHistoryVideo",
    "EaseChatRowHistoryUserCard": "ChatUIKitRowHistoryUserCard",
    "EaseChatRowHistoryVoice": "ChatUIKitRowHistoryVoice",
    "EaseChatRowHistoryLocation": "ChatUIKitRowHistoryLocation",
    "EaseChatRowHistoryText": "ChatUIKitRowHistoryText",
    "EaseChatRowHistoryFile": "ChatUIKitRowHistoryFile",
    "EaseChatRowHistoryBigExpression": "ChatUIKitRowHistoryBigExpression",
    "EaseChatRowHistoryCombine": "ChatUIKitRowHistoryCombine",
    "EaseChatHistoryViewHolderFactory": "ChatUIKitHistoryViewHolderFactory",
    "EaseHistoryImageViewHolder": "ChatUIKitHistoryImageViewHolder",
    "EaseHistoryVideoViewHolder": "ChatUIKitHistoryVideoViewHolder",
    "EaseHistoryUserCardViewHolder": "ChatUIKitHistoryUserCardViewHolder",
    "EaseHistoryExpressionViewHolder": "ChatUIKitHistoryExpressionViewHolder",
    "EaseHistoryFileViewHolder": "ChatUIKitHistoryFileViewHolder",
    "EaseHistoryVoiceViewHolder": "ChatUIKitHistoryVoiceViewHolder",
    "EaseHistoryCombineViewHolder": "ChatUIKitHistoryCombineViewHolder",
    "EaseHistoryTextViewHolder": "ChatUIKitHistoryTextViewHolder",
    "EaseLoadDataType": "ChatUIKitLoadDataType",
    "EaseReactionType": "ChatUIKitReactionType",
    "EaseChatType": "ChatUIKitType",
    "EaseChatExtendMenuIndicatorAdapter": "ChatUIKitExtendMenuIndicatorAdapter",
    "EaseMessagesAdapter": "ChatUIKitMessagesAdapter",
    "EaseChatPinMessageListAdapter": "ChatUIKitPinMessageListAdapter",
    "EaseChatEmojiGridAdapter": "ChatUIKitEmojiGridAdapter",
    "EaseChatExtendMenuAdapter": "ChatUIKitExtendMenuAdapter",
    "EaseChatMessageUrlPreview": "ChatUIKitMessageUrlPreview",
    "EaseMessageSearchResultFragment": "ChatUIKitMessageSearchResultFragment",
    "EaseChatMessageReplyView": "ChatUIKitMessageReplyView",
    "EaseChatExtendMessageReplyView": "ChatUIKitExtendMessageReplyView",
    "EaseUnknownViewHolder": "ChatUIKitUnknownViewHolder",
    "EaseVoiceViewHolder": "ChatUIKitVoiceViewHolder",
    "EaseMessageViewType": "ChatUIKitMessageViewType",
    "EaseCombineViewHolder": "ChatUIKitCombineViewHolder",
    "EaseCustomViewHolder": "ChatUIKitCustomViewHolder",
    "EaseChatViewHolderFactory": "ChatUIKitViewHolderFactory",
    "EaseThreadNotifyViewHolder": "ChatUIKitThreadNotifyViewHolder",
    "EaseUserCardViewHolder": "ChatUIKitUserCardViewHolder",
    "EaseChatRowViewHolder": "ChatUIKitRowViewHolder",
    "EaseExpressionViewHolder": "ChatUIKitExpressionViewHolder",
    "EaseUnsentViewHolder": "ChatUIKitUnsentViewHolder",
    "EaseVideoViewHolder": "ChatUIKitVideoViewHolder",
    "EaseAlertViewHolder": "ChatUIKitAlertViewHolder",
    "EaseTextViewHolder": "ChatUIKitTextViewHolder",
    "EaseImageViewHolder": "ChatUIKitImageViewHolder",
    "EaseFileViewHolder": "ChatUIKitFileViewHolder",
    "EaseThreadUnKnownViewHolder": "ChatUIKitThreadUnKnownViewHolder",
    "EaseMessageSearchResultActivity": "ChatUIKitMessageSearchResultActivity",
    "EaseShowLocalVideoActivity": "ChatUIKitShowLocalVideoActivity",
    "EaseShowBigImageActivity": "ChatUIKitShowBigImageActivity",
    "EaseChatActivity": "UIKitChatActivity",
    "EaseChatHistoryActivity": "ChatUIKitHistoryActivity",
    "EaseShowNormalFileActivity": "ChatUIKitShowNormalFileActivity",
    "EaseShowVideoActivity": "ChatUIKitShowVideoActivity",
    "EaseReportSheetDialog": "ChatUIKitReportSheetDialog",
    "EaseChatAttachmentController": "ChatUIKitAttachmentController",
    "EaseChatPinMessageController": "ChatUIKitPinMessageController",
    "EaseChatMessageReplyController": "ChatUIKitMessageReplyController",
    "EaseChatMessageMultipleSelectController": "ChatUIKitMessageMultipleSelectController",
    "EaseChatDialogController": "ChatUIKitDialogController",
    "EaseChatMessageReportController": "ChatUIKitMessageReportController",
    "EaseChatMentionController": "ChatUIKitMentionController",
    "EaseChatMessageEditController": "ChatUIKitMessageEditController",
    "EaseChatMessageTranslationController": "ChatUIKitMessageTranslationController",
    "EaseChatMessageListScrollAndDataController": "ChatUIKitMessageListScrollAndDataController",
    "EaseChatNotificationController": "ChatUIKitNotificationController",
    "EaseChatAddExtendFunctionViewController": "ChatUIKitAddExtendFunctionViewController",
    "EaseEmojiconPagerView": "ChatUIKitEmojiconPagerView",
    "EaseInputMenuStyle": "ChatUIKitInputMenuStyle",
    "EaseChatLayout": "ChatUIKitLayout",
    "EaseChatNotificationView": "ChatUIKitNotificationView",
    "EaseChatExtendMenu": "ChatUIKitExtendMenu",
    "EaseCustomLayoutManager": "ChatUIKitCustomLayoutManager",
    "EaseEmojiconIndicatorView": "ChatUIKitEmojiconIndicatorView",
    "EaseUnreadNotificationView": "ChatUIKitUnreadNotificationView",
    "EaseChatInputMenu": "ChatUIKitInputMenu",
    "EaseEmojiScrollTabBar": "ChatUIKitEmojiScrollTabBar",
    "EaseEmojiconMenu": "ChatUIKitEmojiconMenu",
    "EaseChatVoiceRecorderDialog": "ChatUIKitVoiceRecorderDialog",
    "EaseChatMessageListLayout": "ChatUIKitMessageListLayout",
    "EaseChatPrimaryMenu": "ChatUIKitPrimaryMenu",
    "EaseMessageForwardDialogFragment": "ChatUIKitMessageForwardDialogFragment",
    "EaseGroupListForwardFragment": "ChatUIKitGroupListForwardFragment",
    "EaseContactForwardFragmentEvent": "ChatUIKitContactForwardFragmentEvent",
    "EaseMessageForwardPagerAdapter": "ChatUIKitMessageForwardPagerAdapter",
    "EaseContactForwardAdapter": "ChatUIKitContactForwardAdapter",
    "EaseGroupListForwardAdapter": "ChatUIKitGroupListForwardAdapter",
    "EaseSearchForwardUserDialogFragment": "ChatUIKitSearchForwardUserDialogFragment",
    "EaseChatMessageMultiSelectHelper": "ChatUIKitMessageMultiSelectHelper",
    "EaseGroupForwardViewHolder": "ChatUIKitGroupForwardViewHolder",
    "EaseContactForwardViewHolder": "ChatUIKitContactForwardViewHolder",
    "EaseChatMultipleSelectMenuView": "ChatUIKitMultipleSelectMenuView",
    "EaseChatExtendMenuItemClickListener": "ChatUIKitExtendMenuItemClickListener",
    "EaseChatPrimaryMenuListener": "ChatUIKitPrimaryMenuListener",
    "EaseEmojiconMenuListener": "ChatUIKitEmojiconMenuListener",
    "EaseGroupMembersListActivity": "ChatUIKitGroupMembersListActivity",
    "EaseGroupMentionBottomSheet": "ChatUIKitGroupMentionBottomSheet",
    "EaseGroupDetailActivity": "ChatUIKitGroupDetailActivity",
    "EaseGroupListActivity": "ChatUIKitGroupListActivity",
    "EaseCreateGroupActivity": "ChatUIKitCreateGroupActivity",
    "EaseGroupDetailEditActivity": "ChatUIKitGroupDetailEditActivity",
    "EaseGroupListFragment": "ChatUIKitGroupListFragment",
    "EaseGroupAddMemberFragment": "ChatUIKitGroupAddMemberFragment",
    "EaseGroupRemoveMemberFragment": "ChatUIKitGroupRemoveMemberFragment",
    "EaseGroupMemberFragment": "ChatUIKitGroupMemberFragment",
    "EaseGroupListConfigBinding": "ChatUIKitGroupListConfigBinding",
    "EaseGroupListConfig": "ChatUIKitGroupListConfig",
    "EaseGroupSelectListAdapter": "ChatUIKitGroupSelectListAdapter",
    "EaseGroupListAdapter": "ChatUIKitGroupListAdapter",
    "EaseGroupMemberListAdapter": "ChatUIKitGroupMemberListAdapter",
    "EaseSelectContactViewHolder": "ChatUIKitSelectContactViewHolder",
    "EaseGroupListViewHolder": "ChatUIKitGroupListViewHolder",
    "EaseSearchUserFragment": "ChatUIKitSearchUserFragment",
    "EaseSearchSelectUserFragment": "ChatUIKitSearchSelectUserFragment",
    "EaseSearchConversationFragment": "ChatUIKitSearchConversationFragment",
    "EaseSearchActivity": "ChatUIKitSearchActivity",
    "EaseSearchForwardUserFragment": "ChatUIKitSearchForwardUserFragment",
    "EaseSearchMessageFragment": "ChatUIKitSearchMessageFragment",
    "EaseSearchMessageAdapter": "ChatUIKitSearchMessageAdapter",
    "EaseSearchUserAdapter": "ChatUIKitSearchUserAdapter",
    "EaseSearchConversationAdapter": "ChatUIKitSearchConversationAdapter",
    "EaseNewRequestsActivity": "ChatUIKitNewRequestsActivity",
    "EaseNewRequestsDetailsActivity": "ChatUIKitNewRequestsDetailsActivity",
    "EaseRequestAdapter": "ChatUIKitRequestAdapter",
    "EaseNewRequestsViewHolder": "ChatUIKitNewRequestsViewHolder",
    "EaseNotificationMsgManager": "ChatUIKitNotificationMsgManager",
    "EaseCreateChatThreadActivity": "ChatUIKitCreateThreadActivity",
    "EaseChatThreadActivity": "ChatUIKitThreadActivity",
    "EaseChatThreadMemberActivity": "ChatUIKitThreadMemberActivity",
    "EaseChatThreadListActivity": "ChatUIKitThreadListActivity",
    "EaseChatThreadListAdapter": "ChatUIKitThreadListAdapter",
    "EaseChatThreadListFragment": "ChatUIKitThreadListFragment",
    "EaseChatThreadMemberFragment": "ChatUIKitThreadMemberFragment",
    "EaseChatThreadFragment": "ChatUIKitThreadFragment",
    "EaseCreateChatThreadFragment": "ChatUIKitCreateThreadFragment",
    "EaseChatThreadAttachmentController": "ChatUIKitThreadAttachmentController",
    "EaseChatThreadController": "ChatUIKitThreadController",
    "EaseChatThreadListViewHolder": "ChatUIKitThreadListViewHolder",
    "EaseChatThreadRole": "ChatUIKitThreadRole",
    "EaseChatMessageThreadView": "ChatUIKitMessageThreadView",
    "EaseConversationListFragment": "ChatUIKitConversationListFragment",
    "EaseConvItemConfig": "ChatUIKitConvItemConfig",
    "EaseConvItemConfigBinding": "ChatUIKitConvItemConfigBinding",
    "EaseConversationListAdapter": "ChatUIKitConversationListAdapter",
    "EaseConversationViewHolderFactory": "ChatUIKitConversationViewHolderFactory",
    "EaseConvViewType": "ChatUIKitConvViewType",
    "EaseConversationViewHolder": "ChatUIKitConversationViewHolder",
    "EaseConvDialogController": "ChatUIKitConvDialogController",
    "EaseConversationListLayout": "ChatUIKitConversationListLayout",
    "EaseBaseSearchFragment": "ChatUIKitBaseSearchFragment",
    "EaseBaseSheetFragmentDialog": "ChatUIKitBaseSheetFragmentDialog",
    "EaseBaseActivity": "ChatUIKitBaseActivity",
    "EaseBaseAdapter": "ChatUIKitBaseAdapter",
    "EaseContainChildBottomSheetFragment": "ChatUIKitContainChildBottomSheetFragment",
    "EaseBaseFullDialogFragment": "ChatUIKitBaseFullDialogFragment",
    "EaseBaseListFragment": "ChatUIKitBaseListFragment",
    "EaseBaseFragment": "ChatUIKitBaseFragment",
    "EaseBaseRecyclerViewAdapter": "ChatUIKitBaseRecyclerViewAdapter",
    "EaseBaseChatExtendMenuAdapter": "ChatUIKitBaseExtendMenuAdapter",
    "EaseMessageListener": "ChatUIKitMessageListener",
    "EaseMultiDeviceListener": "ChatUIKitMultiDeviceListener",
    "EaseChatRoomListener": "UIKitChatRoomListener",
    "EaseConversationListener": "ChatUIKitConversationListener",
    "EaseContactListener": "ChatUIKitContactListener",
    "EaseIMClient": "IChatUIKitClient",
    "EaseConnectionListener": "ChatUIKitConnectionListener",
    "EaseGroupListener": "ChatUIKitGroupListener",
    "EaseBaseFragmentBuilder":"ChatUIKitBaseFragmentBuilder",
    "EaseChatEmojiGridViewHolder":"UIKitChatEmojiGridViewHolder",
    "EaseChatEmojiViewHolderFactory":"UIKitChatEmojiViewHolderFactory",
    "EaseDefaultEmojiIconData":"ChatUIKitDefaultEmojiIconData",
    "EaseEditTextUtils":"ChatUIKitEditTextUtils",
    "EaseEmojiconPagerViewListener":"ChatUIKitEmojiconPagerViewListener",
    "EaseFlowAdapter":"ChatUIKitFlowAdapter",
    "EaseNotificationInfoProvider":"ChatUIKitNotificationInfoProvider",
    "EaseProgressDialog":"ChatUIKitProgressDialog",
    "EaseReactionAdapter":"ChatUIKitReactionAdapter",
    "EaseReactionUserViewHolder":"ChatUIKitReactionUserViewHolder",
    "EaseScrollTabBarItemClickListener":"ChatUIKitScrollTabBarItemClickListener",
    "EaseSearchConversationViewHolder":"ChatUIKitSearchConversationViewHolder",
    "EaseSearchMessageViewHolder":"ChatUIKitSearchMessageViewHolder",
    "EaseSearchType":"ChatUIKitSearchType",
    "EaseSearchUserHolder":"ChatUIKitSearchUserHolder",
    "EaseVoiceRecorderErrorListener":"ChatUIKitVoiceRecorderErrorListener",
    "OnEaseChatReactionErrorListener":"OnChatUIKitReactionErrorListener",
    "IEaseContactResultView":"IUIKitContactResultView",
    "IEaseConvListResultView":"IUIKitConvListResultView",
    "IEaseGroupResultView":"IUIKitGroupResultView",
    "IEaseNotificationResultView":"IUIKitNotificationResultView",
    "IEaseSearchRequest":"IUIKitSearchRequest",
    "IEaseSearchResultView":"IUIKitSearchResultView",
    "EasyIUserMethods":"IUIKitUserMethods",
    "EasyVideoCallback":"IUIKitVideoCallback",
    "EasyVideoPlayer":"UIKitVideoPlayer",
    "EasyVideoProgressCallback":"IUIKitVideoProgressCallback",

    #layout
    "ease_row_received_user_card": "uikit_row_received_user_card",
    "ease_dialog_message_forward": "uikit_dialog_message_forward",
    "ease_row_sent_reply_layout": "uikit_row_sent_reply_layout",
    "ease_contact_list": "uikit_contact_list",
    "ease_chat_menu_item": "uikit_chat_menu_item",
    "ease_activity_chat_thread": "uikit_activity_chat_thread",
    "ease_row_sent_user_card": "uikit_row_sent_user_card",
    "ease_activity_show_local_video": "uikit_activity_show_local_video",
    "ease_layout_new_request_details": "uikit_layout_new_request_details",
    "ease_layout_no_data_show_nothing": "uikit_layout_no_data_show_nothing",
    "ease_item_forward_layout": "uikit_item_forward_layout",
    "ease_fragment_reaction_user_list": "uikit_fragment_reaction_user_list",
    "ease_widget_chat_input_menu_container": "uikit_widget_chat_input_menu_container",
    "ease_item_message_reaction": "uikit_item_message_reaction",
    "ease_item_message_menu_reaction": "uikit_item_message_menu_reaction",
    "ease_layout_group_list": "uikit_layout_group_list",
    "ease_activity_show_file": "uikit_activity_show_file",
    "ease_item_menu": "uikit_item_menu",
    "ease_row_sent_url_preview_layout": "uikit_row_sent_url_preview_layout",
    "ease_widget_emojicon_tab_bar": "uikit_widget_emojicon_tab_bar",
    "ease_pinlist_text_layout": "uikit_pinlist_text_layout",
    "ease_fragment_search_layout": "uikit_fragment_search_layout",
    "ease_widget_chat_message_reaction": "uikit_widget_chat_message_reaction",
    "ease_row_history_message": "uikit_row_history_message",
    "ease_layout_bubble_combine": "uikit_layout_bubble_combine",
    "ease_layout_default_no_data": "uikit_layout_default_no_data",
    "ease_simple_sheet_item": "uikit_simple_sheet_item",
    "ease_activity_create_group_layout": "uikit_activity_create_group_layout",
    "ease_fragment_base_list": "uikit_fragment_base_list",
    "ease_showvideo_activity": "uikit_showvideo_activity",
    "ease_activity_create_chat_thread": "uikit_activity_create_chat_thread",
    "ease_row_history_picture": "uikit_row_history_picture",
    "ease_row_received_location": "uikit_row_received_location",
    "ease_layout_new_request": "uikit_layout_new_request",
    "ease_row_received_combine": "uikit_row_received_combine",
    "ease_row_sent_bigexpression": "uikit_row_sent_bigexpression",
    "ease_row_received_reply_layout": "uikit_row_received_reply_layout",
    "ease_activity_chat": "uikit_activity_chat",
    "ease_layout_item_arrow": "uikit_layout_item_arrow",
    "ease_layout_group_details": "uikit_layout_group_details",
    "ease_item_reaction_user": "uikit_item_reaction_user",
    "ease_activity_contact_add_layout": "uikit_activity_contact_add_layout",
    "ease_row_received_picture": "uikit_row_received_picture",
    "ease_layout_chat_thread_region": "uikit_layout_chat_thread_region",
    "ease_fragment_thread_list": "uikit_fragment_thread_list",
    "ease_row_received_translation_layout": "uikit_row_received_translation_layout",
    "ease_row_thread_notify": "uikit_row_thread_notify",
    "ease_title_bar_icon": "uikit_title_bar_icon",
    "ease_item_conversation_list": "uikit_item_conversation_list",
    "ease_activity_chat_thread_list": "uikit_activity_chat_thread_list",
    "ease_layout_chat": "uikit_layout_chat",
    "ease_row_received_message": "uikit_row_received_message",
    "ease_chat_emoji_scroll_tab_item": "uikit_chat_emoji_scroll_tab_item",
    "ease_pop_operate": "uikit_pop_operate",
    "ease_layout_chat_messages_multi_select_menu": "uikit_layout_chat_messages_multi_select_menu",
    "ease_row_history_combine": "uikit_row_history_combine",
    "ease_layout_report_item": "uikit_layout_report_item",
    "ease_row_history_bigexpression": "uikit_row_history_bigexpression",
    "ease_layout_group_detail_edit": "uikit_layout_group_detail_edit",
    "ease_row_history_file": "uikit_row_history_file",
    "ease_layout_chat_extend_menu": "uikit_layout_chat_extend_menu",
    "ease_row_received_bigexpression": "uikit_row_received_bigexpression",
    "ease_chat_menu_item_horizontal": "uikit_chat_menu_item_horizontal",
    "ease_layout_simple_sheet_dialog": "uikit_layout_simple_sheet_dialog",
    "ease_layout_item_switch": "uikit_layout_item_switch",
    "ease_row_sent_location": "uikit_row_sent_location",
    "ease_row_sent_video": "uikit_row_sent_video",
    "ease_fragment_chat": "uikit_fragment_chat",
    "ease_pinlist_default_layout": "uikit_pinlist_default_layout",
    "ease_row_history_location": "uikit_row_history_location",
    "ease_row_history_video": "uikit_row_history_video",
    "ease_row_sent_combine": "uikit_row_sent_combine",
    "ease_row_received_url_preview_layout": "uikit_row_received_url_preview_layout",
    "ease_layout_chat_report": "uikit_layout_chat_report",
    "ease_row_chat_emoji_big_expression": "uikit_row_chat_emoji_big_expression",
    "ease_chat_voice_recorder": "uikit_chat_voice_recorder",
    "ease_layout_group_member_select_item": "uikit_layout_group_member_select_item",
    "ease_row_sent_file": "uikit_row_sent_file",
    "ease_presence_view": "uikit_presence_view",
    "ease_row_sent_message": "uikit_row_sent_message",
    "ease_row_received_voice": "uikit_row_received_voice",
    "ease_conversation_list": "uikit_conversation_list",
    "ease_pin_message_list_view_group": "uikit_pin_message_list_view_group",
    "ease_dialog_top_drag": "uikit_dialog_top_drag",
    "ease_fragment_thread_create": "uikit_fragment_thread_create",
    "ease_row_sent_picture": "uikit_row_sent_picture",
    "ease_layout_chat_history": "uikit_layout_chat_history",
    "ease_chat_message_list": "uikit_chat_message_list",
    "ease_widget_chat_primary_menu": "uikit_widget_chat_primary_menu",
    "ease_fragment_chat_history": "uikit_fragment_chat_history",
    "ease_layout_item_header": "uikit_layout_item_header",
    "ease_view_base_loading": "uikit_view_base_loading",
    "ease_pinlist_image_layout": "uikit_pinlist_image_layout",
    "ease_chat_emoji_expression_gridview": "uikit_chat_emoji_expression_gridview",
    "ease_dialog_chat_reactions": "uikit_dialog_chat_reactions",
    "ease_item_chat_thread_list_item": "uikit_item_chat_thread_list_item",
    "ease_row_unsent_message": "uikit_row_unsent_message",
    "ease_activity_search_layout": "uikit_activity_search_layout",
    "ease_chat_extend_indicator_item": "uikit_chat_extend_indicator_item",
    "ease_row_sent_translation_layout": "uikit_row_sent_translation_layout",
    "ease_widget_title_bar": "uikit_widget_title_bar",
    "ease_layout_group_list_item": "uikit_layout_group_list_item",
    "ease_row_chat_emoji_expression": "uikit_row_chat_emoji_expression",
    "ease_row_received_file": "uikit_row_received_file",
    "ease_layout_unread_notification": "uikit_layout_unread_notification",
    "ease_fragment_group_list": "uikit_fragment_group_list",
    "ease_layout_search": "uikit_layout_search",
    "ease_activity_show_big_image": "uikit_activity_show_big_image",
    "ease_widget_chat_emojicon": "uikit_widget_chat_emojicon",
    "ease_dialog_message_reactions": "uikit_dialog_message_reactions",
    "ease_row_received_video": "uikit_row_received_video",
    "ease_layout_contact_item": "uikit_layout_contact_item",
    "ease_layout_invitation_item": "uikit_layout_invitation_item",
    "ease_activity_thread_member_layout": "uikit_activity_thread_member_layout",
    "ease_chat_message_edit_dialog": "uikit_chat_message_edit_dialog",
    "ease_layout_group_select_contact": "uikit_layout_group_select_contact",
    "ease_row_history_voice": "uikit_row_history_voice",
    "ease_row_thread_unknown": "uikit_row_thread_unknown",
    "ease_layout_custom_dialog": "uikit_layout_custom_dialog",
    "ease_dialog_menu": "uikit_dialog_menu",
    "ease_fragment_contain_title_base": "uikit_fragment_contain_title_base",
    "easet_layout_group_mention": "uikit_layout_group_mention",
    "ease_widget_chat_message_reply": "uikit_widget_chat_message_reply",
    "ease_fragment_dialog_full": "uikit_fragment_dialog_full",
    "ease_row_sent_voice": "uikit_row_sent_voice",
    "ease_item_message_reaction_tab": "uikit_item_message_reaction_tab",
    "ease_activity_group_member_layout": "uikit_activity_group_member_layout",
    "ease_item_select_text_pop": "uikit_item_select_text_pop",
    "ease_activity_block_list": "uikit_activity_block_list",
    "easy_include_controls": "uikit_include_controls",
    #xml
    "ease_chat_row_receive_bubble_bg": "uikit_chat_row_receive_bubble_bg",
    "ease_chat_row_send_message_reply_bg": "uikit_chat_row_send_message_reply_bg",
    "ease_url_preview_receive_bubble_bg": "uikit_url_preview_receive_bubble_bg",
    "ease_chat_row_sent_bubble_bg": "uikit_chat_row_sent_bubble_bg",
    "ease_search_bg": "uikit_search_bg",
    "ease_chat_row_receive_message_reply_bg": "uikit_chat_row_receive_message_reply_bg",
    "ease_url_preview_sent_bubble_bg": "uikit_url_preview_sent_bubble_bg",
    "ease_chat_dimens": "uikit_chat_dimens",
    "ease_configures": "uikit_configures",
    "ease_style": "uikit_style",
    "ease_dialog_from_bottom_anim_in": "uikit_dialog_from_bottom_anim_in",
    "ease_chat_extend_menu_indicator_divider": "uikit_chat_extend_menu_indicator_divider",
    "ease_chat_primary_menu_setmode_keyboard_btn": "uikit_chat_primary_menu_setmode_keyboard_btn",
    "ease_report_checkbox_bg_selector_style": "uikit_report_checkbox_bg_selector_style",
    "ease_contact_add_button_bg": "uikit_contact_add_button_bg",
    "ease_checkbox_bg_selector_style": "uikit_checkbox_bg_selector_style",
    "ease_conv_item_selected": "uikit_conv_item_selected",
    "ease_group_edit_bg": "uikit_group_edit_bg",
    "ease_ripple_click_gray": "uikit_ripple_click_gray",
    "ease_chat_forward_btn_bg_normal": "uikit_chat_forward_btn_bg_normal",
    "ease_dialog_border": "uikit_dialog_border",
    "ease_chat_row_receive_triangle": "uikit_chat_row_receive_triangle",
    "ease_chat_row_video_length_bg": "uikit_chat_row_video_length_bg",
    "ease_chat_recyclerview_item_shadow": "uikit_chat_recyclerview_item_shadow",
    "ease_thread_region_bubble": "uikit_thread_region_bubble",
    "ease_chat_primary_menu_input_bg": "uikit_chat_primary_menu_input_bg",
    "ease_common_tab_bg": "uikit_common_tab_bg",
    "ease_chat_primary_menu_send_btn_selector": "uikit_chat_primary_menu_send_btn_selector",
    "ease_dialog_top_drag_bg": "uikit_dialog_top_drag_bg",
    "ease_chat_item_multi_selector": "uikit_chat_item_multi_selector",
    "ease_progressbar_loading_bg": "uikit_progressbar_loading_bg",
    "ease_chat_message_reaction_item_bg_selected": "uikit_chat_message_reaction_item_bg_selected",
    "ease_detail_item_bg_radius8": "uikit_detail_item_bg_radius8",
    "ease_chat_takepic_selector": "uikit_chat_takepic_selector",
    "ease_chat_message_menu_reaction_item_bg_selector": "uikit_chat_message_menu_reaction_item_bg_selector",
    "ease_bg_toolbar_status": "uikit_bg_toolbar_status",
    "ease_chat_record_delete_bg": "uikit_chat_record_delete_bg",
    "ease_chat_message_reaction_tab_item_bg_pressed": "uikit_chat_message_reaction_tab_item_bg_pressed",
    "ease_dialog_create_group_bg": "uikit_dialog_create_group_bg",
    "ease_chat_row_receive_location_content_bg": "uikit_chat_row_receive_location_content_bg",
    "ease_chat_message_reaction_item_bg_normal": "uikit_chat_message_reaction_item_bg_normal",
    "ease_dialog_custom_bg": "uikit_dialog_custom_bg",
    "ease_chat_emoji_pager_send_btn_selector": "uikit_chat_emoji_pager_send_btn_selector",
    "ease_chat_emoji_item_bg_normal": "uikit_chat_emoji_item_bg_normal",
    "ease_chat_message_edit_button_selector": "uikit_chat_message_edit_button_selector",
    "ease_chat_image_selector": "uikit_chat_image_selector",
    "ease_chat_voice_unread_icon": "uikit_chat_voice_unread_icon",
    "ease_custom_dialog_action_bg": "uikit_custom_dialog_action_bg",
    "ease_chat_menu_extend_indicator_selector": "uikit_chat_menu_extend_indicator_selector",
    "ease_chat_emoji_delete_button_bg": "uikit_chat_emoji_delete_button_bg",
    "ease_conv_item_unread_count_bg": "uikit_conv_item_unread_count_bg",
    "ease_default_divider_list": "uikit_default_divider_list",
    "ease_sheet_bg_radius16_light": "uikit_sheet_bg_radius16_light",
    "ease_chat_avatar_status_bg": "uikit_chat_avatar_status_bg",
    "ease_chat_row_receive_location_bubble_bg": "uikit_chat_row_receive_location_bubble_bg",
    "ease_chat_message_menu_reaction_item_bg_selected": "uikit_chat_message_menu_reaction_item_bg_selected",
    "ease_chat_message_reaction_item_bg_selector": "uikit_chat_message_reaction_item_bg_selector",
    "ease_widget_chat_message_reply_background": "uikit_widget_chat_message_reply_background",
    "ease_view_default_touch_shadow_bg": "uikit_view_default_touch_shadow_bg",
    "ease_chat_message_reaction_item_bg_pressed": "uikit_chat_message_reaction_item_bg_pressed",
    "ease_chat_loading_progress_bar": "uikit_chat_loading_progress_bar",
    "ease_dialog_input_bg": "uikit_dialog_input_bg",
    "ease_chat_message_menu_reaction_item_bg_normal": "uikit_chat_message_menu_reaction_item_bg_normal",
    "ease_switch_thumb_selector": "uikit_switch_thumb_selector",
    "ease_conv_item_pinned": "uikit_conv_item_pinned",
    "ease_progressbar_loading": "uikit_progressbar_loading",
    "ease_msg_state_failed_resend": "uikit_msg_state_failed_resend",
    "ease_chat_emoji_expression_gridview_divider": "uikit_chat_emoji_expression_gridview_divider",
    "ease_chat_forward_btn_bg_pressed": "uikit_chat_forward_btn_bg_pressed",
    "ease_chat_report_tag": "uikit_chat_report_tag",
    "ease_chat_voice_record_bg": "uikit_chat_voice_record_bg",
    "ease_switch_track_selector": "uikit_switch_track_selector",
    "ease_chat_row_send_location_content_bg": "uikit_chat_row_send_location_content_bg",
    "ease_chat_record_send_bg": "uikit_chat_record_send_bg",
    "ease_chat_primary_menu_more_button_selector": "uikit_chat_primary_menu_more_button_selector",
    "ease_chat_primary_menu_setmode_voice_btn": "uikit_chat_primary_menu_setmode_voice_btn",
    "ease_live_input_cursor_bg": "uikit_live_input_cursor_bg",
    "ease_chat_row_send_location_bubble_bg": "uikit_chat_row_send_location_bubble_bg",
    "ease_chat_message_reaction_tab_item_bg_selector": "uikit_chat_message_reaction_tab_item_bg_selector",
    "ease_shape_message_forward_tab_layout_indicator": "uikit_shape_message_forward_tab_layout_indicator",
    "ease_conv_item_unread_dot_bg": "uikit_conv_item_unread_dot_bg",
    "ease_chat_emoji_item_bg_selector": "uikit_chat_emoji_item_bg_selector",
    "ease_dialog_drag_bg": "uikit_dialog_drag_bg",
    "ease_sheet_top_icon": "uikit_sheet_top_icon",
    "ease_msg_unread": "uikit_msg_unread",
    "ease_chat_message_reaction_tab_item_bg_normal": "uikit_chat_message_reaction_tab_item_bg_normal",
    "ease_chat_message_edit_root_bg": "uikit_chat_message_edit_root_bg",
    "ease_default_navigation_icon": "uikit_default_navigation_icon",
    "ease_chat_emoji_item_bg_pressed": "uikit_chat_emoji_item_bg_pressed",
    "ease_chat_extend_menu_wxstyle_bg": "uikit_chat_extend_menu_wxstyle_bg",
    # "ease_show_head_toast_bg": "chat_show_head_toast_bg",
    "ease_chat_forward_btn_bg_selector": "uikit_chat_forward_btn_bg_selector",
    "ease_shape_popup_radius_8": "uikit_shape_popup_radius_8",
    "ease_invitation_action_bg": "uikit_invitation_action_bg",
    "ease_chat_message_menu_reaction_item_bg_pressed": "uikit_chat_message_menu_reaction_item_bg_pressed",
    "ease_chat_row_file_icon_bg": "uikit_chat_row_file_icon_bg",
    "ease_selector_custom_dialog_tv_right_color": "uikit_selector_custom_dialog_tv_right_color",
    "ease_selector_add_text_change_color": "uikit_selector_add_text_change_color",
    "ease_selector_chat_multiple_select_del_button_color": "uikit_selector_chat_multiple_select_del_button_color",
    "ease_selector_remove_text_change_color": "uikit_selector_remove_text_change_color",
    "ease_selector_chat_forward_btn_text_color": "uikit_selector_chat_forward_btn_text_color",
    "ease_selector_custom_dialog_right_bg": "uikit_selector_custom_dialog_right_bg",
    "ease_selector_chat_multiple_select_forward_button_color": "uikit_selector_chat_multiple_select_forward_button_color",
    "ease_selector_text_change_1_bg": "uikit_selector_text_change_1_bg",
    "ease_selector_change_text_color": "uikit_selector_change_text_color",
    "ease_selector_action_text_change_color": "uikit_selector_action_text_change_color",
    "ease_chat_colors": "uikit_chat_colors",
    "ease_group_styles": "uikit_group_styles",
    "ease_colors": "uikit_colors",
    "ease_styles": "uikit_styles",
    "ease_contact_colors": "uikit_contact_colors",
    "ease_request_styles": "uikit_request_styles",
    "ease_conversation_styles": "uikit_conversation_styles",
    "ease_request_colors": "uikit_request_colors",
    "ease_conversation_colors": "uikit_conversation_colors",
    "ease_conversation_dimens": "uikit_conversation_dimens",
    "ease_contact_styles": "uikit_contact_styles",
    "ease_chat_styles": "uikit_chat_styles",
    "ease_dimens": "uikit_dimens",
    "ease_common_color": "uikit_common_color",
    "ease_conversation_attrs": "uikit_conversation_attrs",
    "ease_attrs": "uikit_attrs",
    "ease_strings": "uikit_strings",
    "ease_ids": "uikit_ids",
    "ease_chat_thread_style": "uikit_chat_thread_style",
    "ease_chat_attrs": "uikit_chat_attrs",
    "ease_arrays": "uikit_arrays",
    "ease_group_colors": "uikit_group_colors",

    #png
    "ease_default_avatar": "uikit_default_avatar",
    "ease_icon_combine": "uikit_icon_combine",
    "ease_loading_progress": "uikit_loading_progress",
    "ease_chat_image_pressed": "uikit_chat_image_pressed",
    "ease_chat_item_menu_edit": "uikit_chat_item_menu_edit",
    "ease_chat_item_menu_forward": "uikit_chat_item_menu_forward",
    "ease_chat_quote_icon_file": "uikit_chat_quote_icon_file",
    "ease_type_select_btn_pressed": "uikit_type_select_btn_pressed",
    "ease_chat_item_menu_topic": "uikit_chat_item_menu_topic",
    "ease_chat_quote_icon_voice": "uikit_chat_quote_icon_voice",
    "ease_chatfrom_voice_playing": "uikit_chatfrom_voice_playing",
    "ease_dot_emojicon_selected": "uikit_dot_emojicon_selected",
    "ease_icon_thread_topic": "uikit_icon_thread_topic",
    "ease_icon_add": "uikit_icon_add",
    "ease_chat_quote_default_video": "uikit_chat_quote_default_video",
    "ease_chatting_setmode_keyboard_btn_pressed": "uikit_chatting_setmode_keyboard_btn_pressed",
    "ease_default_image": "uikit_default_image",
    "ease_presence_leave": "uikit_presence_leave",
    "ease_chat_message_edit_no_change": "uikit_chat_message_edit_no_change",
    "ease_msg_status_read": "uikit_msg_status_read",
    "ease_chat_item_menu_copy": "uikit_chat_item_menu_copy",
    "ease_checkbox_select": "uikit_checkbox_select",
    "ease_type_select_btn_nor": "uikit_type_select_btn_nor",
    "ease_delete_expression": "uikit_delete_expression",
    "ease_chat_quote_icon_image": "uikit_chat_quote_icon_image",
    "ease_conversation_muted": "uikit_conversation_muted",
    "ease_presence_custom": "uikit_presence_custom",
    "ease_chatting_emoji_btn_enable": "uikit_chatting_emoji_btn_enable",
    "ease_chat_quote_default_image": "uikit_chat_quote_default_image",
    "ease_presence_offline": "uikit_presence_offline",
    "ease_chat_image_normal": "uikit_chat_image_normal",
    "ease_chat_voice_file_delete": "uikit_chat_voice_file_delete",
    "ease_chat_emoji_backspace": "uikit_chat_emoji_backspace",
    "ease_checkbox_available": "uikit_checkbox_available",
    "ease_chat_item_menu_unsent": "uikit_chat_item_menu_unsent",
    "ease_bubble_msg": "uikit_bubble_msg",
    "ease_icon_down_arrow": "uikit_icon_down_arrow",
    "ease_chat_quote_icon_video": "uikit_chat_quote_icon_video",
    "ease_chatto_voice_playing_f1": "uikit_chatto_voice_playing_f1",
    "ease_chatfrom_voice_playing_f1": "uikit_chatfrom_voice_playing_f1",
    "ease_msg_state_fail_resend_pressed": "uikit_msg_state_fail_resend_pressed",
    "ease_chat_input_primary_send_icon": "uikit_chat_input_primary_send_icon",
    "ease_presence_arrow_left": "uikit_presence_arrow_left",
    "ease_chat_voice_send": "uikit_chat_voice_send",
    "ease_chat_quote_message_attachment": "uikit_chat_quote_message_attachment",
    "ease_chatto_voice_playing_f2": "uikit_chatto_voice_playing_f2",
    "ease_chat_quote_icon_cancel": "uikit_chat_quote_icon_cancel",
    "ease_chatfrom_voice_playing_f2": "uikit_chatfrom_voice_playing_f2",
    "ease_conv_new_group": "uikit_conv_new_group",
    "ease_default_group_avatar": "uikit_default_group_avatar",
    "ease_chatfrom_voice_playing_f3": "uikit_chatfrom_voice_playing_f3",
    "ease_chatto_voice_playing_f3": "uikit_chatto_voice_playing_f3",
    "ease_chat_item_multi_selected": "uikit_chat_item_multi_selected",
    "ease_msg_status_sent": "uikit_msg_status_sent",
    "ease_chat_quote_message_bigemoji": "uikit_chat_quote_message_bigemoji",
    "ease_chat_voice_icon": "uikit_chat_voice_icon",
    "ease_chat_item_menu_translation": "uikit_chat_item_menu_translation",
    "ease_chat_item_multi_no_select": "uikit_chat_item_multi_no_select",
    "ease_chatto_voice_playing": "uikit_chatto_voice_playing",
    "ease_search_msg": "uikit_search_msg",
    "ease_chat_message_edit_changed": "uikit_chat_message_edit_changed",
    "ease_icon_chat_pininfo_light": "uikit_icon_chat_pininfo_light",
    "ease_checkbox_unselect": "uikit_checkbox_unselect",
    "ease_video_play_btn_small_nor": "uikit_video_play_btn_small_nor",
    "ease_topic_count_icon": "uikit_topic_count_icon",
    "ease_chat_inputmenu_quote_cancel_icon": "uikit_chat_inputmenu_quote_cancel_icon",
    "ease_chatting_setmode_keyboard_btn_normal": "uikit_chatting_setmode_keyboard_btn_normal",
    "ease_chat_item_menu_reply": "uikit_chat_item_menu_reply",
    "ease_icon_pin_message": "uikit_icon_pin_message",
    "ease_chat_takepic_normal": "uikit_chat_takepic_normal",
    "ease_chatting_setmode_voice_btn_normal": "uikit_chatting_setmode_voice_btn_normal",
    "ease_copy_id": "uikit_copy_id",
    "ease_chat_takepic_pressed": "uikit_chat_takepic_pressed",
    "ease_msg_state_fail_resend": "uikit_msg_state_fail_resend",
    "ease_chat_item_menu_report": "uikit_chat_item_menu_report",
    "ease_dot_emojicon_unselected": "uikit_dot_emojicon_unselected",
    "ease_chat_item_menu_location": "uikit_chat_item_menu_location",
    "ease_add_member_dark": "uikit_add_member_dark",
    "ease_icon_chat_pininfo_dark": "uikit_icon_chat_pininfo_dark",
    "ease_presence_busy": "uikit_presence_busy",
    "ease_chat_row_file_icon": "uikit_chat_row_file_icon",
    "ease_msg_status_received": "uikit_msg_status_received",
    "ease_chat_location": "uikit_chat_location",
    "ease_conv_add_contact": "uikit_conv_add_contact",
    "ease_chatting_setmode_voice_btn_pressed": "uikit_chatting_setmode_voice_btn_pressed",
    "ease_presence_do_not_disturb": "uikit_presence_do_not_disturb",
    "ease_default_expression": "uikit_default_expression",
    "ease_presence_online": "uikit_presence_online",
    "ease_icon_arrow_left_thick": "uikit_icon_arrow_left_thick",
    "ease_icon_delete": "uikit_icon_delete",
    "ease_chat_quote_icon_combine": "uikit_chat_quote_icon_combine",
    "ease_chat_quote_icon_user_card": "uikit_chat_quote_icon_user_card",
    "ease_chat_send_icon": "uikit_chat_send_icon",
    "ease_chat_emoji_send": "uikit_chat_emoji_send",
    "ease_chat_item_menu_delete": "uikit_chat_item_menu_delete",
    "ease_default_video_thumbnail": "uikit_default_video_thumbnail",
    "ease_conv_new_chat": "uikit_conv_new_chat",
    "ease_chatting_emoji_btn_normal": "uikit_chatting_emoji_btn_normal",
    "ease_chat_item_menu_multi": "uikit_chat_item_menu_multi",
    # "ease_slidetab_bg_press.9": "uikit_slidetab_bg_press.9",
    "ease_menu_group_topic": "uikit_menu_group_topic",
    "ease_menu_multiple_select": "uikit_menu_multiple_select",
    "ease_dialog_input_clear_light": "uikit_dialog_input_clear_light",
    "ease_titlebar_back": "uikit_titlebar_back",
    "ease_video_camera": "uikit_video_camera",
    "ease_chevron_right": "uikit_chevron_right",
    "ease_do_not_disturb": "uikit_do_not_disturb",
    "ease_empty_layout": "uikit_empty_layout",
    "ease_title_menu_dark": "uikit_title_menu_dark",
    "ease_ic_arrow": "uikit_ic_arrow",
    "ease_dialog_input_clear_dark": "uikit_dialog_input_clear_dark",
    "ease_icon_loading": "uikit_icon_loading",
    "ease_phone_pick": "uikit_phone_pick",
    "ease_remove_member": "uikit_remove_member",
    "ease_remove_member_dark": "uikit_remove_member_dark",
    "ease_titlebar_back_dark": "uikit_titlebar_back_dark",
    "ease_mention_all": "uikit_mention_all",
    "ease_report_checkbox_select_bg": "uikit_report_checkbox_select_bg",
    "ease_title_menu": "uikit_title_menu",

    #tag
    "ease_chat_history": "uikit_chat_history",

}
#仅涉及到改文件内容，不涉及改文件名
extra_strings_map = {
    #value
    "EASE_RECORD_ERROR":"UIKIT_RECORD_ERROR",
    #viewBinding
    "EaseWidgetTitleBarBinding": "UikitWidgetTitleBarBinding",
    "EasePresenceViewBinding": "UikitPresenceViewBinding",
    "EaseLayoutSimpleSheetDialogBinding": "UikitLayoutSimpleSheetDialogBinding",
    "EaseDialogMenuBinding": "UikitDialogMenuBinding",
    "EaseItemSelectTextPopBinding": "UikitItemSelectTextPopBinding",
    "EaseActivityBlockListBinding": "UikitActivityBlockListBinding",
    "EaseActivityContactAddLayoutBinding": "UikitActivityContactAddLayoutBinding",
    "EaseLayoutItemHeaderBinding": "UikitLayoutItemHeaderBinding",
    "EaseLayoutGroupSelectContactBinding": "UikitLayoutGroupSelectContactBinding",
    "EaseLayoutContactItemBinding": "UikitLayoutContactItemBinding",
    "EaseFragmentChatBinding": "UikitFragmentChatBinding",
    "EaseFragmentReactionUserListBinding": "UikitFragmentReactionUserListBinding",
    "EaseDialogMessageReactionsBinding": "UikitDialogMessageReactionsBinding",
    "EaseItemMessageReactionTabBinding": "UikitItemMessageReactionTabBinding",
    "EaseItemMessageReactionBinding": "UikitItemMessageReactionBinding",
    "EaseWidgetChatMessageReactionBinding": "UikitWidgetChatMessageReactionBinding",
    "EaseDialogChatReactionsBinding": "UikitDialogChatReactionsBinding",
    "EaseItemMessageMenuReactionBinding": "UikitItemMessageMenuReactionBinding",
    "EaseItemReactionUserBinding": "UikitItemReactionUserBinding",
    "EasePinlistDefaultLayoutBinding": "UikitPinlistDefaultLayoutBinding",
    "EasePinlistTextLayoutBinding": "UikitPinlistTextLayoutBinding",
    "EasePinlistImageLayoutBinding": "UikitPinlistImageLayoutBinding",
    "EaseLayoutChatHistoryBinding": "UikitLayoutChatHistoryBinding",
    "EaseFragmentChatHistoryBinding": "UikitFragmentChatHistoryBinding",
    "EaseRowChatEmojiBigExpressionBinding": "UikitRowChatEmojiBigExpressionBinding",
    "EaseRowChatEmojiExpressionBinding": "UikitRowChatEmojiExpressionBinding",
    "EaseWidgetChatMessageReplyBinding": "UikitWidgetChatMessageReplyBinding",
    "EaseActivityShowFileBinding": "UikitActivityShowFileBinding",
    "EaseActivityChatBinding": "UikitActivityChatBinding",
    "EaseActivityShowBigImageBinding": "UikitActivityShowBigImageBinding",
    "EaseShowvideoActivityBinding": "UikitShowvideoActivityBinding",
    "EaseActivityShowLocalVideoBinding": "UikitActivityShowLocalVideoBinding",
    "EaseLayoutChatReportBinding": "UikitLayoutChatReportBinding",
    "EaseLayoutChatBinding": "UikitLayoutChatBinding",
    "EaseChatEmojiExpressionGridviewBinding": "UikitChatEmojiExpressionGridviewBinding",
    "EaseChatVoiceRecorderBinding": "UikitChatVoiceRecorderBinding",
    "EaseLayoutUnreadNotificationBinding": "UikitLayoutUnreadNotificationBinding",
    "EaseWidgetChatPrimaryMenuBinding": "UikitWidgetChatPrimaryMenuBinding",
    "EaseWidgetChatInputMenuContainerBinding": "UikitWidgetChatInputMenuContainerBinding",
    "EaseWidgetEmojiconTabBarBinding": "UikitWidgetEmojiconTabBarBinding",
    "EaseWidgetChatEmojiconBinding": "UikitWidgetChatEmojiconBinding",
    "EaseLayoutChatExtendMenuBinding": "UikitLayoutChatExtendMenuBinding",
    "EaseChatMessageListBinding": "UikitChatMessageListBinding",
    "EaseDialogMessageForwardBinding": "UikitDialogMessageForwardBinding",
    "EaseItemForwardLayoutBinding": "UikitItemForwardLayoutBinding",
    "EaseLayoutChatMessagesMultiSelectMenuBinding": "UikitLayoutChatMessagesMultiSelectMenuBinding",
    "EaseActivityCreateGroupLayoutBinding": "UikitActivityCreateGroupLayoutBinding",
    "EaseActivityGroupMemberLayoutBinding": "UikitActivityGroupMemberLayoutBinding",
    "EasetLayoutGroupMentionBinding": "UikitLayoutGroupMentionBinding",
    "EaseLayoutGroupDetailsBinding": "UikitLayoutGroupDetailsBinding",
    "EaseLayoutGroupListBinding": "UikitLayoutGroupListBinding",
    "EaseLayoutGroupDetailEditBinding": "UikitLayoutGroupDetailEditBinding",
    "EaseFragmentGroupListBinding": "UikitFragmentGroupListBinding",
    "EaseLayoutGroupListItemBinding": "UikitLayoutGroupListItemBinding",
    "EaseLayoutGroupMemberSelectItemBinding": "UikitLayoutGroupMemberSelectItemBinding",
    "EaseActivitySearchLayoutBinding": "UikitActivitySearchLayoutBinding",
    "EaseLayoutNewRequestDetailsBinding": "UikitLayoutNewRequestDetailsBinding",
    "EaseLayoutNewRequestBinding": "UikitLayoutNewRequestBinding",
    "EaseLayoutInvitationItemBinding": "UikitLayoutInvitationItemBinding",
    "EaseActivityChatThreadListBinding": "UikitActivityChatThreadListBinding",
    "EaseActivityChatThreadBinding": "UikitActivityChatThreadBinding",
    "EaseActivityThreadMemberLayoutBinding": "UikitActivityThreadMemberLayoutBinding",
    "EaseItemChatThreadListItemBinding": "UikitItemChatThreadListItemBinding",
    "EaseFragmentThreadCreateBinding": "UikitFragmentThreadCreateBinding",
    "EaseFragmentThreadListBinding": "UikitFragmentThreadListBinding",
    "EaseLayoutChatThreadRegionBinding": "UikitLayoutChatThreadRegionBinding",
    "EaseItemConversationListBinding": "UikitItemConversationListBinding",
    "EaseConversationListBinding": "UikitConversationListBinding",
    "EaseFragmentContainTitleBaseBinding": "UikitFragmentContainTitleBaseBinding",
    "EaseFragmentDialogFullBinding": "UikitFragmentDialogFullBinding",
    "EaseFragmentSearchLayoutBinding": "UikitFragmentSearchLayoutBinding",
    "EaseFragmentBaseListBinding": "UikitFragmentBaseListBinding",
    "EaseLayoutCustomDialogBinding": "UikitLayoutCustomDialogBinding",

    #R.styleable.
    "EaseChatMessageListLayout_ease_chat_item_text_size": "ChatUIKitMessageListLayout_ease_chat_item_text_size",
    "EaseChatMessageListLayout_ease_chat_item_text_color": "ChatUIKitMessageListLayout_ease_chat_item_text_color",
    "EaseChatMessageListLayout_ease_chat_item_min_height": "ChatUIKitMessageListLayout_ease_chat_item_min_height",
    "EaseChatMessageListLayout_ease_chat_item_time_text_size": "ChatUIKitMessageListLayout_ease_chat_item_time_text_size",
    "EaseChatMessageListLayout_ease_chat_item_time_text_color": "ChatUIKitMessageListLayout_ease_chat_item_time_text_color",
    "EaseChatMessageListLayout_ease_chat_item_time_background": "ChatUIKitMessageListLayout_ease_chat_item_time_background",
    "EaseChatMessageListLayout_ease_chat_item_avatar_default_src": "ChatUIKitMessageListLayout_ease_chat_item_avatar_default_src",
    "EaseChatMessageListLayout_ease_chat_item_avatar_shape_type": "ChatUIKitMessageListLayout_ease_chat_item_avatar_shape_type",
    "EaseChatMessageListLayout_ease_chat_item_sender_background": "ChatUIKitMessageListLayout_ease_chat_item_sender_background",
    "EaseChatMessageListLayout_ease_chat_item_receiver_background": "ChatUIKitMessageListLayout_ease_chat_item_receiver_background",
    "EaseChatMessageListLayout_ease_chat_item_show_nickname": "ChatUIKitMessageListLayout_ease_chat_item_show_nickname",
    "EaseChatMessageListLayout_ease_chat_item_show_avatar": "ChatUIKitMessageListLayout_ease_chat_item_show_avatar",
    "EaseChatMessageListLayout_ease_chat_item_hide_receiver_avatar": "ChatUIKitMessageListLayout_ease_chat_item_hide_receiver_avatar",
    "EaseChatMessageListLayout_ease_chat_item_hide_sender_avatar": "ChatUIKitMessageListLayout_ease_chat_item_hide_sender_avatar",
    "EaseChatMessageListLayout_ease_chat_item_show_type": "ChatUIKitMessageListLayout_ease_chat_item_show_type",
    "EaseChatMessageReplyView_ease_chat_message_reply_is_sender": "ChatUIKitMessageReplyView_ease_chat_message_reply_is_sender",
    "EaseChatMessageReplyView_ease_chat_message_reply_is_history": "ChatUIKitMessageReplyView_ease_chat_message_reply_is_history",
    "EaseChatMessageTranslationView_ease_chat_message_translation_is_sender": "ChatUIKitMessageTranslationView_ease_chat_message_translation_is_sender",
    "EaseChatMessageTranslationView_ease_chat_message_translation_is_history": "ChatUIKitMessageTranslationView_ease_chat_message_translation_is_history",
    "EaseChatMessageUrlPreview_ease_chat_message_preview_is_sender": "ChatUIKitMessageUrlPreview_ease_chat_message_preview_is_sender",
    "EaseEmojiconMenu_emojiconColumns": "ChatUIKitEmojiconMenu_emojiconColumns",
    "EaseEmojiconMenu_bigEmojiconRows": "ChatUIKitEmojiconMenu_bigEmojiconRows",
    "EaseChatExtendMenu_numColumns": "ChatUIKitExtendMenu_numColumns",
    "EaseChatExtendMenu_numRows": "ChatUIKitExtendMenu_numRows",
    "EaseConversationListLayout_ease_con_item_title_text_size": "ChatUIKitConversationListLayout_ease_con_item_title_text_size",
    "EaseConversationListLayout_ease_con_item_title_text_color": "ChatUIKitConversationListLayout_ease_con_item_title_text_color",
    "EaseConversationListLayout_ease_con_item_content_text_size": "ChatUIKitConversationListLayout_ease_con_item_content_text_size",
    "EaseConversationListLayout_ease_con_item_content_text_color": "ChatUIKitConversationListLayout_ease_con_item_content_text_color",
    "EaseConversationListLayout_ease_con_item_date_text_size": "ChatUIKitConversationListLayout_ease_con_item_date_text_size",
    "EaseConversationListLayout_ease_con_item_date_text_color": "ChatUIKitConversationListLayout_ease_con_item_date_text_color",
    "EaseConversationListLayout_ease_con_item_mention_text_size": "ChatUIKitConversationListLayout_ease_con_item_mention_text_size",
    "EaseConversationListLayout_ease_con_item_mention_text_color": "ChatUIKitConversationListLayout_ease_con_item_mention_text_color",
    "EaseConversationListLayout_ease_con_item_unread_dot_position": "ChatUIKitConversationListLayout_ease_con_item_unread_dot_position",
    "EaseConversationListLayout_ease_con_item_unread_style": "ChatUIKitConversationListLayout_ease_con_item_unread_style",
    "EaseConversationListLayout_ease_con_item_avatar_size": "ChatUIKitConversationListLayout_ease_con_item_avatar_size",
    "EaseConversationListLayout_ease_con_item_avatar_shape_type": "ChatUIKitConversationListLayout_ease_con_item_avatar_shape_type",
    "EaseConversationListLayout_ease_con_item_avatar_border_width": "ChatUIKitConversationListLayout_ease_con_item_avatar_border_width",
    "EaseConversationListLayout_ease_con_item_avatar_border_color": "ChatUIKitConversationListLayout_ease_con_item_avatar_border_color",
    "EaseConversationListLayout_ease_con_item_height": "ChatUIKitConversationListLayout_ease_con_item_height",
    "EaseMenuItemView_menuOrientation": "ChatUIKitMenuItemView_menuOrientation",
    "EaseMenuItemView_contentGravity": "ChatUIKitMenuItemView_contentGravity",
    "EaseArrowItemView_arrowItemTitle": "ChatUIKitArrowItemView_arrowItemTitle",
    "EaseArrowItemView_arrowItemTitleColor": "ChatUIKitArrowItemView_arrowItemTitleColor",
    "EaseArrowItemView_arrowItemTitleStyle": "ChatUIKitArrowItemView_arrowItemTitleStyle",
    "EaseArrowItemView_arrowItemTitleSize": "ChatUIKitArrowItemView_arrowItemTitleSize",
    "EaseArrowItemView_arrowItemSubTitle": "ChatUIKitArrowItemView_arrowItemSubTitle",
    "EaseArrowItemView_arrowItemSubTitleColor": "ChatUIKitArrowItemView_arrowItemSubTitleColor",
    "EaseArrowItemView_arrowItemShowSubTitle": "ChatUIKitArrowItemView_arrowItemShowSubTitle",
    "EaseArrowItemView_arrowItemSubTitleStyle": "ChatUIKitArrowItemView_arrowItemSubTitleStyle",
    "EaseArrowItemView_arrowItemSubTitleSize": "ChatUIKitArrowItemView_arrowItemSubTitleSize",
    "EaseArrowItemView_arrowItemContent": "ChatUIKitArrowItemView_arrowItemContent",
    "EaseArrowItemView_arrowItemContentColor": "ChatUIKitArrowItemView_arrowItemContentColor",
    "EaseArrowItemView_arrowItemContentSize": "ChatUIKitArrowItemView_arrowItemContentSize",
    "EaseArrowItemView_arrowItemShowDivider": "ChatUIKitArrowItemView_arrowItemShowDivider",
    "EaseArrowItemView_arrowItemShowArrow": "ChatUIKitArrowItemView_arrowItemShowArrow",
    "EaseArrowItemView_arrowItemShowAvatar": "ChatUIKitArrowItemView_arrowItemShowAvatar",
    "EaseArrowItemView_arrowItemArrowSrc": "ChatUIKitArrowItemView_arrowItemArrowSrc",
    "EaseArrowItemView_arrowItemAvatarSrc": "ChatUIKitArrowItemView_arrowItemAvatarSrc",
    "EaseArrowItemView_arrowItemAvatarHeight": "ChatUIKitArrowItemView_arrowItemAvatarHeight",
    "EaseArrowItemView_arrowItemAvatarWidth": "ChatUIKitArrowItemView_arrowItemAvatarWidth",
    "EaseFlowLayout_alignRight": "ChatUIKitFlowLayout_alignRight",
    "EaseFlowLayout_horizontalMargin": "ChatUIKitFlowLayout_horizontalMargin",
    "EaseSearchEditText_search_edit_drawable_left_height": "ChatUIKitSearchEditText_search_edit_drawable_left_height",
    "EaseSearchEditText_search_edit_drawable_left_width": "ChatUIKitSearchEditText_search_edit_drawable_left_width",
    "EaseSearchEditText_search_edit_drawable_right_height": "ChatUIKitSearchEditText_search_edit_drawable_right_height",
    "EaseSearchEditText_search_edit_drawable_right_width": "ChatUIKitSearchEditText_search_edit_drawable_right_width",
    "EaseSearchView_search_drawable_icon": "ChatUIKitSearchView_search_drawable_icon",
    "EaseSearchView_search_drawable_icon_tint": "ChatUIKitSearchView_search_drawable_icon_tint",
    "EaseSearchView_search_text_hint": "ChatUIKitSearchView_search_text_hint",
    "EaseSearchView_search_text_color": "ChatUIKitSearchView_search_text_color",
    "EaseSearchView_search_text_size": "ChatUIKitSearchView_search_text_size",
    "EaseSearchView_search_text": "ChatUIKitSearchView_search_text",
    "EaseSearchView_search_gravity": "ChatUIKitSearchView_search_gravity",
    "EaseSearchView_search_drawable_padding": "ChatUIKitSearchView_search_drawable_padding",
    "EaseSidebar_ease_side_bar_top_text": "ChatUIKitSidebar_ease_side_bar_top_text",
    "EaseSidebar_ease_side_bar_text_color": "ChatUIKitSidebar_ease_side_bar_text_color",
    "EaseSidebar_ease_side_bar_focus_bg_color": "ChatUIKitSidebar_ease_side_bar_focus_bg_color",
    "EaseSidebar_ease_side_bar_delay_disappear_time": "ChatUIKitSidebar_ease_side_bar_delay_disappear_time",
    "EaseSidebar_ease_side_bar_text_size": "ChatUIKitSidebar_ease_side_bar_text_size",
    "EaseSidebar_ease_side_bar_background": "ChatUIKitSidebar_ease_side_bar_background",
    "EaseSidebar_ease_side_bar_head_arrays": "ChatUIKitSidebar_ease_side_bar_head_arrays",
    "EaseTitleBar_titleBarDisplayHomeAsUpEnabled": "ChatUIKitTitleBar_titleBarDisplayHomeAsUpEnabled",
    "EaseTitleBar_titleBarReplaceActionBar": "ChatUIKitTitleBar_titleBarReplaceActionBar",
    "EaseTitleBar_titleBarLogoSize": "ChatUIKitTitleBar_titleBarLogoSize",
    "EaseTitleBar_titleBarLogo": "ChatUIKitTitleBar_titleBarLogo",
    "EaseTitleBar_titleBarMenuTitleColor": "ChatUIKitTitleBar_titleBarMenuTitleColor",
    "EaseTitleBar_titleBarMenuIconTint": "ChatUIKitTitleBar_titleBarMenuIconTint",
    "EaseTitleBar_titleBarTitleTextAppearance": "ChatUIKitTitleBar_titleBarTitleTextAppearance",
    "EaseTitleBar_titleBarSubtitleTextAppearance": "ChatUIKitTitleBar_titleBarSubtitleTextAppearance",
    "EaseTitleBar_titleBarTitle": "ChatUIKitTitleBar_titleBarTitle",
    "EaseTitleBar_titleBarSubtitle": "ChatUIKitTitleBar_titleBarSubtitle",
    "EaseTitleBar_titleBarTitleCenter": "ChatUIKitTitleBar_titleBarTitleCenter",
    "EaseTitleBar_titleBarPopupTheme": "ChatUIKitTitleBar_titleBarPopupTheme",
    "EaseTitleBar_titleBarNavigationIcon": "ChatUIKitTitleBar_titleBarNavigationIcon",
    "EaseTitleBar_titleBarNavigationIconTint": "ChatUIKitTitleBar_titleBarNavigationIconTint",
    "EaseTitleBar_titleBarNavigationContentDescription": "ChatUIKitTitleBar_titleBarNavigationContentDescription",
    "EaseTitleBar_titleBarLogoDescription": "ChatUIKitTitleBar_titleBarLogoDescription",
    "EaseTitleBar_titleBarTitleTextColor": "ChatUIKitTitleBar_titleBarTitleTextColor",
    "EaseTitleBar_titleBarSubtitleTextColor": "ChatUIKitTitleBar_titleBarSubtitleTextColor",
    "EaseTitleBar_titleBarMenu": "ChatUIKitTitleBar_titleBarMenu",
    "EaseWaveView_ease_wave_color": "ChatUIKitWaveView_ease_wave_color",
    "EaseWaveView_ease_wave_width": "ChatUIKitWaveView_ease_wave_width",
    "EaseWaveView_ease_wave_height": "ChatUIKitWaveView_ease_wave_height",
    "EaseWaveView_ease_wave_radius": "ChatUIKitWaveView_ease_wave_radius",
    "EaseWaveView_ease_wave_stroke_width": "ChatUIKitWaveView_ease_wave_stroke_width",
    "EaseWaveView_ease_wave_move_distance": "ChatUIKitWaveView_ease_wave_move_distance",
    "EaseWaveView_ease_wave_start_alpha": "ChatUIKitWaveView_ease_wave_start_alpha",
    "EaseWaveView_ease_wave_end_alpha": "ChatUIKitWaveView_ease_wave_end_alpha",
    "EaseWaveView_ease_wave_duration": "ChatUIKitWaveView_ease_wave_duration",
    "EaseWaveView_ease_wave_show_bg_wave": "ChatUIKitWaveView_ease_wave_show_bg_wave",
    "EaseWaveView_ease_wave_bg_height": "ChatUIKitWaveView_ease_wave_bg_height",
    "EaseWaveView_ease_wave_bg_width": "ChatUIKitWaveView_ease_wave_bg_width",
    "EaseWaveView_ease_wave_bg_radius": "ChatUIKitWaveView_ease_wave_bg_radius",
    "EaseWaveView_ease_wave_bg_stroke_width": "ChatUIKitWaveView_ease_wave_bg_stroke_width",
    "EaseWaveView_ease_wave_bg_color": "ChatUIKitWaveView_ease_wave_bg_color",
    "EasyVideoPlayer_easy_source": "UIKitVideoPlayer_easy_source",
    "EasyVideoPlayer_easy_playDrawable": "UIKitVideoPlayer_easy_playDrawable",
    "EasyVideoPlayer_easy_pauseDrawable": "UIKitVideoPlayer_easy_pauseDrawable",
    "EasyVideoPlayer_easy_hideControlsOnPlay": "UIKitVideoPlayer_easy_hideControlsOnPlay",
    "EasyVideoPlayer_easy_autoPlay": "UIKitVideoPlayer_easy_autoPlay",
    "EasyVideoPlayer_easy_disableControls": "UIKitVideoPlayer_easy_disableControls",
    "EasyVideoPlayer_easy_themeColor": "UIKitVideoPlayer_easy_themeColor",
    "EasyVideoPlayer_easy_autoFullscreen": "UIKitVideoPlayer_easy_autoFullscreen",
    "EasyVideoPlayer_easy_loop": "UIKitVideoPlayer_easy_loop",
    "EaseImageView_ease_border_color": "ChatUIKitImageView_ease_border_color",
    "EaseImageView_ease_border_width": "ChatUIKitImageView_ease_border_width",
    "EaseImageView_ease_press_alpha": "ChatUIKitImageView_ease_press_alpha",
    "EaseImageView_ease_press_color": "ChatUIKitImageView_ease_press_color",
    "EaseImageView_ease_radius": "ChatUIKitImageView_ease_radius",
    "EaseImageView_ease_shape_type": "ChatUIKitImageView_image_shape_type",
    "ease_shape_type": "image_shape_type",


    #uikit_strings.xml里的单词
    "ease_search_text_hint": "uikit_search_text_hint",
    "ease_sheet_cancel": "uikit_sheet_cancel",
    "ease_dialog_black_title": "uikit_dialog_black_title",
    "ease_dialog_black": "uikit_dialog_black",
    "ease_dialog_clear": "uikit_dialog_clear",
    "ease_dialog_delete_contact_title": "uikit_dialog_delete_contact_title",
    "ease_dialog_delete_contact_subtitle": "uikit_dialog_delete_contact_subtitle",
    "ease_dialog_edit_input_id_hint": "uikit_dialog_edit_input_id_hint",
    "ease_dialog_cancel": "uikit_dialog_cancel",
    "ease_dialog_confirm": "uikit_dialog_confirm",
    "ease_message_unread_count_max": "uikit_message_unread_count_max",
    "ease_location_recv": "uikit_location_recv",
    "ease_location_prefix": "uikit_location_prefix",
    "ease_location": "uikit_location",
    "ease_picture": "uikit_picture",
    "ease_video": "uikit_video",
    "ease_file": "uikit_file",
    "ease_voice": "uikit_voice",
    "ease_custom": "uikit_custom",
    "ease_combine": "uikit_combine",
    "ease_user_card": "uikit_user_card",
    "ease_dynamic_expression": "uikit_dynamic_expression",
    "ease_chat_were_not_send_msg": "uikit_chat_were_not_send_msg",
    "ease_all_members": "uikit_all_members",
    "ease_chat_were_mentioned": "uikit_chat_were_mentioned",
    "ease_chat_were_mentioned_all": "uikit_chat_were_mentioned_all",
    "ease_search_conversation_hint": "uikit_search_conversation_hint",
    "ease_conversation_menu_action_more": "uikit_conversation_menu_action_more",
    "ease_conversation_title": "uikit_conversation_title",
    "ease_conv_action_new_conversation": "uikit_conv_action_new_conversation",
    "ease_conv_action_add_contact": "uikit_conv_action_add_contact",
    "ease_conv_action_create_group": "uikit_conv_action_create_group",
    "ease_conv_dialog_add_contact": "uikit_conv_dialog_add_contact",
    "ease_chat_primary_menu_button_send": "uikit_chat_primary_menu_button_send",
    "ease_chat_primary_menu_button_pushtotalk": "uikit_chat_primary_menu_button_pushtotalk",
    "ease_chat_primary_menu_input_hint": "uikit_chat_primary_menu_input_hint",
    "ease_chat_search_message": "uikit_chat_search_message",
    "ease_attach_picture": "uikit_attach_picture",
    "ease_attach_take_pic": "uikit_attach_take_pic",
    "ease_attach_location": "uikit_attach_location",
    "ease_attach_video": "uikit_attach_video",
    "ease_attach_file": "uikit_attach_file",
    "ease_attach_contact_card": "uikit_attach_contact_card",
    "ease_group_ack_read_count": "uikit_group_ack_read_count",
    "ease_custom_message": "uikit_custom_message",
    "ease_have_uploaded": "uikit_have_uploaded",
    "ease_chat_unknown_type": "uikit_chat_unknown_type",
    "ease_msg_recall_by_self": "uikit_msg_recall_by_self",
    "ease_msg_recall_by_user": "uikit_msg_recall_by_user",
    "ease_is_download_voice_click_later": "uikit_is_download_voice_click_later",
    "ease_action_reply": "uikit_action_reply",
    "ease_action_copy": "uikit_action_copy",
    "ease_action_forward": "uikit_action_forward",
    "ease_action_recall": "uikit_action_recall",
    "ease_action_delete": "uikit_action_delete",
    "ease_action_edit": "uikit_action_edit",
    "ease_action_report": "uikit_action_report",
    "ease_action_translation": "uikit_action_translation",
    "ease_action_hide_translation": "uikit_action_hide_translation",
    "ease_action_multi_select": "uikit_action_multi_select",
    "ease_action_thread": "uikit_action_thread",
    "ease_action_pin": "uikit_action_pin",
    "ease_chat_record_voice_record": "uikit_chat_record_voice_record",
    "ease_chat_record_voice_recording": "uikit_chat_record_voice_recording",
    "ease_chat_record_voice_play": "uikit_chat_record_voice_play",
    "ease_chat_record_voice_playing": "uikit_chat_record_voice_playing",
    "ease_chat_record_voice_remain": "uikit_chat_record_voice_remain",
    "ease_chat_record_voice_time": "uikit_chat_record_voice_time",
    "ease_download_the_pictures": "uikit_download_the_pictures",
    "ease_image_expired": "uikit_image_expired",
    "ease_download_the_pictures_new": "uikit_download_the_pictures_new",
    "ease_downwaiting": "uikit_downwaiting",
    "ease_failed_to_download_file": "uikit_failed_to_download_file",
    "ease_file_expired": "uikit_file_expired",
    "ease_is_down_please_wait": "uikit_is_down_please_wait",
    "ease_video_expired": "uikit_video_expired",
    "ease_emoji": "uikit_emoji",
    "ease_thread": "uikit_thread",
    "ease_chat_inputmenu_quote_reply_to": "uikit_chat_inputmenu_quote_reply_to",
    "ease_error_message_not_exist": "uikit_error_message_not_exist",
    "ease_quote_message_not_exist": "uikit_quote_message_not_exist",
    "ease_message_reply_emoji_type": "uikit_message_reply_emoji_type",
    "ease_message_reply_image_type": "uikit_message_reply_image_type",
    "ease_message_reply_video_type": "uikit_message_reply_video_type",
    "ease_message_reply_file_type": "uikit_message_reply_file_type",
    "ease_message_reply_voice_type": "uikit_message_reply_voice_type",
    "ease_message_reply_location_type": "uikit_message_reply_location_type",
    "ease_message_reply_custom_type": "uikit_message_reply_custom_type",
    "ease_message_reply_combine_type": "uikit_message_reply_combine_type",
    "ease_message_reply_location_content": "uikit_message_reply_location_content",
    "ease_message_reply_file_content": "uikit_message_reply_file_content",
    "ease_message_reply_voice_content": "uikit_message_reply_voice_content",
    "ease_message_reply_unknown_type": "uikit_message_reply_unknown_type",
    "ease_cancel": "uikit_cancel",
    "ease_message_edit": "uikit_message_edit",
    "ease_message_edited": "uikit_message_edited",
    "ease_fail_to_edit": "uikit_fail_to_edit",
    "ease_chat_message_edit_edited": "uikit_chat_message_edit_edited",
    "ease_chat_message_user_card_label": "uikit_chat_message_user_card_label",
    "ease_chat_message_user_card_select_title": "uikit_chat_message_user_card_select_title",
    "ease_chat_message_user_card_share_content": "uikit_chat_message_user_card_share_content",
    "ease_chat_dialog_delete_title": "uikit_chat_dialog_delete_title",
    "ease_chat_dialog_delete_content": "uikit_chat_dialog_delete_content",
    "ease_chat_dialog_recall_title": "uikit_chat_dialog_recall_title",
    "ease_chat_dialog_resend_title": "uikit_chat_dialog_resend_title",
    "ease_chat_dialog_delete_multi_message_title": "uikit_chat_dialog_delete_multi_message_title",
    "ease_chat_dialog_delete_one_message_title": "uikit_chat_dialog_delete_one_message_title",
    "ease_chat_copy_success": "uikit_chat_copy_success",
    "ease_chat_reaction_reach_limit": "uikit_chat_reaction_reach_limit",
    "ease_chat_reply_forwarded": "uikit_chat_reply_forwarded",
    "ease_message_forward": "uikit_message_forward",
    "ease_message_forward_to_contact": "uikit_message_forward_to_contact",
    "ease_message_forward_to_group": "uikit_message_forward_to_group",
    "ease_combine_default": "uikit_combine_default",
    "ease_combine_compatible_default": "uikit_combine_compatible_default",
    "ease_message_unread_count": "uikit_message_unread_count",
    "ease_chat_new_conversation": "uikit_chat_new_conversation",
    "ease_chat_new_group_welcome": "uikit_chat_new_group_welcome",
    "ease_conv_menu_item_silent": "uikit_conv_menu_item_silent",
    "ease_conv_menu_item_unsilent": "uikit_conv_menu_item_unsilent",
    "ease_conv_menu_item_pin": "uikit_conv_menu_item_pin",
    "ease_conv_menu_item_unpin": "uikit_conv_menu_item_unpin",
    "ease_conv_menu_item_read": "uikit_conv_menu_item_read",
    "ease_conv_menu_item_delete": "uikit_conv_menu_item_delete",
    "ease_prompt": "uikit_prompt",
    "ease_ok": "uikit_ok",
    "ease_date_language_zh": "uikit_date_language_zh",
    "ease_date_just": "uikit_date_just",
    "ease_data_format_hour": "uikit_data_format_hour",
    "ease_data_format_today": "uikit_data_format_today",
    "ease_loading": "uikit_loading",
    "ease_contact_title": "uikit_contact_title",
    "ease_delete_contact": "uikit_delete_contact",
    "ease_clear_history": "uikit_clear_history",
    "ease_message_no_disturbance": "uikit_message_no_disturbance",
    "ease_contact_header_request": "uikit_contact_header_request",
    "ease_contact_header_group": "uikit_contact_header_group",
    "ease_contact_search": "uikit_contact_search",
    "ease_contact_add": "uikit_contact_add",
    "ease_contact_number": "uikit_contact_number",
    "ease_header_request": "uikit_header_request",
    "ease_header_group": "uikit_header_group",
    "ease_dialog_right_text": "uikit_dialog_right_text",
    "ease_contact_add_dialog_title": "uikit_contact_add_dialog_title",
    "ease_new_invitation_title": "uikit_new_invitation_title",
    "ease_new_invitation": "uikit_new_invitation",
    "ease_invitation_detail_action": "uikit_invitation_detail_action",
    "ease_invitation_reason": "uikit_invitation_reason",
    "ease_invitation_action_add": "uikit_invitation_action_add",
    "ease_invitation_action_added": "uikit_invitation_action_added",
    "ease_agreed_to": "uikit_agreed_to",
    "ease_detail_item_message": "uikit_detail_item_message",
    "ease_detail_item_audio": "uikit_detail_item_audio",
    "ease_detail_item_video": "uikit_detail_item_video",
    "ease_detail_item_search_msg": "uikit_detail_item_search_msg",
    "ease_new_group_title": "uikit_new_group_title",
    "ease_new_group_count": "uikit_new_group_count",
    "ease_group_detail_member_list": "uikit_group_detail_member_list",
    "ease_group_detail_member_count": "uikit_group_detail_member_count",
    "ease_group_detail_my_notes": "uikit_group_detail_my_notes",
    "ease_group_detail_group_name": "uikit_group_detail_group_name",
    "ease_group_detail_group_id": "uikit_group_detail_group_id",
    "ease_group_detail_group_describe": "uikit_group_detail_group_describe",
    "ease_group_detail_change_owner": "uikit_group_detail_change_owner",
    "ease_group_detail_destroy": "uikit_group_detail_destroy",
    "ease_group_detail_leave": "uikit_group_detail_leave",
    "ease_group_detail_leave_dialog": "uikit_group_detail_leave_dialog",
    "ease_group_detail_leave_dialog_destroy": "uikit_group_detail_leave_dialog_destroy",
    "ease_group_detail_leave_dialog_des": "uikit_group_detail_leave_dialog_des",
    "ease_group_detail_leave_dialog_owner_des": "uikit_group_detail_leave_dialog_owner_des",
    "ease_group_count": "uikit_group_count",
    "ease_group_change_name": "uikit_group_change_name",
    "ease_group_change_name_count": "uikit_group_change_name_count",
    "ease_group_change_describe": "uikit_group_change_describe",
    "ease_group_change_describe_count": "uikit_group_change_describe_count",
    "ease_group_change_save": "uikit_group_change_save",
    "ease_group_change_owner_title": "uikit_group_change_owner_title",
    "ease_group_change_owner": "uikit_group_change_owner",
    "ease_group_remove_members": "uikit_group_remove_members",
    "ease_group_remove_members_2": "uikit_group_remove_members_2",
    "ease_group_remove_members_more_than_3": "uikit_group_remove_members_more_than_3",
    "ease_group_member_count": "uikit_group_member_count",
    "ease_add_group_member_title": "uikit_add_group_member_title",
    "ease_add_group_member_select_count": "uikit_add_group_member_select_count",
    "ease_remove_group_member_title": "uikit_remove_group_member_title",
    "ease_remove_group_member_select_count": "uikit_remove_group_member_select_count",
    "ease_group_mention_title": "uikit_group_mention_title",
    "ease_group_mention_all": "uikit_group_mention_all",
    "ease_report_title": "uikit_report_title",
    "ease_report_reason": "uikit_report_reason",
    "ease_report_bottom_left": "uikit_report_bottom_left",
    "ease_report_bottom_right": "uikit_report_bottom_right",
    "ease_report_success": "uikit_report_success",
    "ease_notifier_channel_name": "uikit_notifier_channel_name",
    "ease_notifier_default_content": "uikit_notifier_default_content",
    "ease_translation_status": "uikit_translation_status",
    "ease_thread_list_title": "uikit_thread_list_title",
    "ease_thread_affiliation_group": "uikit_thread_affiliation_group",
    "ease_thread_region_count": "uikit_thread_region_count",
    "ease_thread_region_no_msg": "uikit_thread_region_no_msg",
    "ease_thread_member_title": "uikit_thread_member_title",
    "ease_thread_remove_from_topic": "uikit_thread_remove_from_topic",
    "ease_thread_delete_topic_title": "uikit_thread_delete_topic_title",
    "ease_thread_delete_topic_subtitle": "uikit_thread_delete_topic_subtitle",
    "ease_thread_notify_content": "uikit_thread_notify_content",
    "ease_thread_notify_detail": "uikit_thread_notify_detail",
    "ease_thread_edit_title": "uikit_thread_edit_title",
    "ease_thread_edit_name_count": "uikit_thread_edit_name_count",
    "ease_thread_unknown_message": "uikit_thread_unknown_message",
    "ease_block_title": "uikit_block_title",
    "ease_switch_block_title": "uikit_switch_block_title",
    "ease_search_block_user": "uikit_search_block_user",
    "ease_url_preview_parsing": "uikit_url_preview_parsing",
    "ease_pin_list_item_delete": "uikit_pin_list_item_delete",
    "ease_pin_list_item_confirm_delete": "uikit_pin_list_item_confirm_delete",


}
# 预置的字符串映射
string_map = files_map.copy()
string_map.update(extra_strings_map)



#特殊处理 例如.9.png等
# string_map["ease_show_head_toast_bg"] = "chat_show_head_toast_bg"
#string_map["ease_slidetab_bg_press"] = "chat_slidetab_bg_press"


def do_rename_files(root_dir, files_map):
    rename_count = 0
    for dirpath, dirnames, filenames in os.walk(root_dir):
        for filename in filenames:
            name, ext = os.path.splitext(filename)
            if name in files_map:
                old_path = os.path.join(dirpath, filename)
                new_filename = files_map[name] + ext
                new_path = os.path.join(dirpath, new_filename)
                os.rename(old_path, new_path)
                print(f'Renamed: {old_path} to {new_path}')
                rename_count += 1
    return rename_count

def process_file(file_path, string_map):
    # 按行替换
    # with open(file_path, 'r') as f:
    #     lines = f.readlines()
    #
    # new_lines = []
    # modified = False
    # for line_num, line in enumerate(lines, start=1):
    #     # 如果行中包含 'R.styleable.'，跳过替换
    #     if 'R.styleable.' in line:
    #         new_lines.append(line)
    #         continue
    #
    #     new_line = line
    #     for old_string, new_string in string_map.items():
    #         pattern = r'\b' + re.escape(old_string) + r'\b'
    #         new_line = re.sub(pattern, new_string, new_line)
    #     if new_line != line:
    #         modified = True
    #     new_lines.append(new_line)
    #
    # if modified:
    #     with open(file_path, 'w') as f:
    #         f.writelines(new_lines)
    #     print(f'Modified content in: {file_path}')
    #     return 1

    #整体替换，加快脚本速度,会导致R.styleable.EaseChatMessageReplyView->R.styleable.ChatUIKitMessageReplyView
    with open(file_path, 'r') as file:
        old_content = file.read()

    new_content=old_content
        # Use regex to replace only whole words
    for old_string, new_string in string_map.items():
            pattern = r'\b' + re.escape(old_string) + r'\b'
            new_content = re.sub(pattern, new_string, new_content)
    if new_content != old_content:
        with open(file_path, 'w') as file:
            file.write(new_content)
        print(f'Modified content in: {file_path}')
        return 1
    return 0

def do_replace_content(root_dir, string_map, max_workers=None):
    modify_count = 0
    if max_workers is None:
        max_workers = os.cpu_count()*2  # 推荐的最大线程数
        #打印空行
        print("\n")
        print(f"------------Using {max_workers} workers.---------------")
        print("\n")
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = []
        for dirpath, dirnames, filenames in os.walk(root_dir):
            for filename in filenames:
                name, ext = os.path.splitext(filename)
                if ext not in ['.xml', '.kt', '.java']:
                    print(f"Skipping file with unsupported extension: {filename}")
                    continue
                # if ext == '.xml' and 'layout' not in dirpath:
                #     print(f"Skipping XML file not in layout directory: {filename}")
                #     continue
                file_path = os.path.join(dirpath, filename)
                futures.append(executor.submit(process_file, file_path, string_map))
        for future in as_completed(futures):
            modify_count += future.result()
    return modify_count

def main(directory, rename_files, replace_content):
    start_time = time.time()  # 记录开始时间
    if not os.path.isdir(directory):
        print(f"Error: Directory {directory} does not exist.")
        return

    files_renamed_count = 0
    files_content_changed_count = 0

    if rename_files:
        print("Starting file renaming process...")
        files_renamed_count = do_rename_files(directory, files_map)


    if replace_content:
        print("Starting file content replacement process...")
        files_content_changed_count = do_replace_content(directory, string_map)

    end_time = time.time()  # 记录结束时间
    total_time = end_time - start_time  # 计算总耗时
    # 将总耗时转换为分秒格式
    minutes, seconds = divmod(total_time, 60)

    print(f"Total files renamed: {files_renamed_count}")
    print(f"Total files with content changed: {files_content_changed_count}")
    print(f"Total time taken: {int(minutes)} minutes and {seconds:.2f} seconds")  # 打印总耗时

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Rename files and replace content in a directory.")
    parser.add_argument('directory', type=str, help='The target directory to process.')
    parser.add_argument('--rename-files', action='store_true', help='Rename files according to the predefined mapping.')
    parser.add_argument('--replace-content', action='store_true', help='Replace content in files according to the predefined mapping.')

    args = parser.parse_args()

    main(args.directory, args.rename_files, args.replace_content)
